// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/user.proto

package user

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Player account profile.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username of the account.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// First name of the user.
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Last name of the user.
	LastName string `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Optional website URL.
	Website string `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	// Whether the profile and portfolio are public.
	IsPublic bool `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	// Whether the user is an admin.
	IsAdmin bool `protobuf:"varint,7,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	// Whether the user is banned.
	IsBanned bool `protobuf:"varint,8,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`
	// Creation timestamp of the account.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Current cash balance in USD.
	Balance float64 `protobuf:"fixed64,10,opt,name=balance,proto3" json:"balance,omitempty"`
	// Current stock portfolio holdings.
	Portfolio map[string]*PortfolioItem `protobuf:"bytes,11,rep,name=portfolio,proto3" json:"portfolio,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether the user is participating in the current competition.
	IsParticipating bool `protobuf:"varint,12,opt,name=is_participating,json=isParticipating,proto3" json:"is_participating,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *User) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *User) GetPortfolio() map[string]*PortfolioItem {
	if x != nil {
		return x.Portfolio
	}
	return nil
}

func (x *User) GetIsParticipating() bool {
	if x != nil {
		return x.IsParticipating
	}
	return false
}

// Public representation of a user profile.
type PublicProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username of the account.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// First name of the user.
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Last name of the user.
	LastName string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Optional website URL.
	Website string `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	// Current cash balance in USD.
	Balance float64 `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	// Current stock portfolio holdings.
	Portfolio     map[string]*PortfolioItem `protobuf:"bytes,6,rep,name=portfolio,proto3" json:"portfolio,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicProfile) Reset() {
	*x = PublicProfile{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicProfile) ProtoMessage() {}

func (x *PublicProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicProfile.ProtoReflect.Descriptor instead.
func (*PublicProfile) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *PublicProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PublicProfile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *PublicProfile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *PublicProfile) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *PublicProfile) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *PublicProfile) GetPortfolio() map[string]*PortfolioItem {
	if x != nil {
		return x.Portfolio
	}
	return nil
}

// PortfolioItem represents a single stock holding in a user's portfolio.
type PortfolioItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stock ticker symbol.
	StockSymbol string `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"`
	// The quantity of shares owned.
	Quantity float64 `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// The average purchase price of the shares.
	AveragePrice  float64 `protobuf:"fixed64,3,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioItem) Reset() {
	*x = PortfolioItem{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioItem) ProtoMessage() {}

func (x *PortfolioItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioItem.ProtoReflect.Descriptor instead.
func (*PortfolioItem) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *PortfolioItem) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *PortfolioItem) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PortfolioItem) GetAveragePrice() float64 {
	if x != nil {
		return x.AveragePrice
	}
	return 0
}

// Request to register a new user.
type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique username (3-20 characters).
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Secure password (min 8 characters).
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// First name of the user.
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Last name of the user.
	LastName string `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Optional website URL.
	Website string `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	// Accept terms of service flag.
	AgbAccepted   bool `protobuf:"varint,6,opt,name=agb_accepted,json=agbAccepted,proto3" json:"agb_accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CreateUserRequest) GetAgbAccepted() bool {
	if x != nil {
		return x.AgbAccepted
	}
	return false
}

// Response containing the registered user.
type CreateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Details of the registered user.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request to update the current profile.
type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated first name.
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Updated last name.
	LastName string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Updated website URL.
	Website string `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	// Sets whether the profile is public.
	IsPublic bool `protobuf:"varint,4,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	// Field mask to specify which fields should be updated.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *UpdateUserRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *UpdateUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Response containing the updated profile.
type UpdateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Details of the updated user.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request to authenticate a user.
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User's username.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// User's password.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Response containing the authenticated user.
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Details of the authenticated user.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request to logout.
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

// Response for logout.
type LogoutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status or success message.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to fetch the current user profile.
type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

// Response containing the current user profile.
type GetMeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Details of the current user.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetMeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request to fetch a public profile.
type GetPublicProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username of the profile to fetch.
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicProfileRequest) Reset() {
	*x = GetPublicProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicProfileRequest) ProtoMessage() {}

func (x *GetPublicProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicProfileRequest.ProtoReflect.Descriptor instead.
func (*GetPublicProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetPublicProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Response containing the public profile.
type GetPublicProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public details of the user.
	Profile       *PublicProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicProfileResponse) Reset() {
	*x = GetPublicProfileResponse{}
	mi := &file_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicProfileResponse) ProtoMessage() {}

func (x *GetPublicProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicProfileResponse.ProtoReflect.Descriptor instead.
func (*GetPublicProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetPublicProfileResponse) GetProfile() *PublicProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xe5\x03\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsite\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublic\x12\x19\n" +
	"\bis_admin\x18\a \x01(\bR\aisAdmin\x12\x1b\n" +
	"\tis_banned\x18\b \x01(\bR\bisBanned\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\abalance\x18\n" +
	" \x01(\x01R\abalance\x12:\n" +
	"\tportfolio\x18\v \x03(\v2\x1c.user.v1.User.PortfolioEntryR\tportfolio\x12)\n" +
	"\x10is_participating\x18\f \x01(\bR\x0fisParticipating\x1aT\n" +
	"\x0ePortfolioEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.user.v1.PortfolioItemR\x05value:\x028\x01J\x04\b\x01\x10\x02\"\xb6\x02\n" +
	"\rPublicProfile\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x18\n" +
	"\awebsite\x18\x04 \x01(\tR\awebsite\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x01R\abalance\x12C\n" +
	"\tportfolio\x18\x06 \x03(\v2%.user.v1.PublicProfile.PortfolioEntryR\tportfolio\x1aT\n" +
	"\x0ePortfolioEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.user.v1.PortfolioItemR\x05value:\x028\x01\"s\n" +
	"\rPortfolioItem\x12!\n" +
	"\fstock_symbol\x18\x01 \x01(\tR\vstockSymbol\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12#\n" +
	"\raverage_price\x18\x03 \x01(\x01R\faveragePrice\"\xc4\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsite\x12!\n" +
	"\fagb_accepted\x18\x06 \x01(\bR\vagbAccepted\"7\n" +
	"\x12CreateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"\xc3\x01\n" +
	"\x11UpdateUserRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x18\n" +
	"\awebsite\x18\x03 \x01(\tR\awebsite\x12\x1b\n" +
	"\tis_public\x18\x04 \x01(\bR\bisPublic\x12;\n" +
	"\vupdate_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"7\n" +
	"\x12UpdateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"2\n" +
	"\rLoginResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"\x0f\n" +
	"\rLogoutRequest\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x0e\n" +
	"\fGetMeRequest\"2\n" +
	"\rGetMeResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"5\n" +
	"\x17GetPublicProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"L\n" +
	"\x18GetPublicProfileResponse\x120\n" +
	"\aprofile\x18\x01 \x01(\v2\x16.user.v1.PublicProfileR\aprofile2\x86\x05\n" +
	"\vUserService\x12_\n" +
	"\n" +
	"CreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\x1b.user.v1.CreateUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12S\n" +
	"\x05Login\x12\x15.user.v1.LoginRequest\x1a\x16.user.v1.LoginResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/sessions\x12h\n" +
	"\x06Logout\x12\x16.user.v1.LogoutRequest\x1a\x17.user.v1.LogoutResponse\"-\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"CookieAuth\x12\x00\x82\xd3\xe4\x93\x02\x12*\x10/api/v1/sessions\x12d\n" +
	"\x05GetMe\x12\x15.user.v1.GetMeRequest\x1a\x16.user.v1.GetMeResponse\",\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"CookieAuth\x12\x00\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/profile\x12v\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\x1b.user.v1.UpdateUserResponse\"/\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"CookieAuth\x12\x00\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/api/v1/profile\x12y\n" +
	"\x10GetPublicProfile\x12 .user.v1.GetPublicProfileRequest\x1a!.user.v1.GetPublicProfileResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/users/{username}B\x87\x02\x92A\xbb\x01\x12d\n" +
	"\x10User Service API\x12IAPI for managing user registration, authentication, and profile settings.2\x051.0.0ZS\n" +
	"Q\n" +
	"\n" +
	"CookieAuth\x12C\b\x02\x121Authentication cookie 'auth_token' containing JWT\x1a\n" +
	"auth_token \x02ZFgithub.com/tmythicator/ticker-rush/backend/internal/proto/user/v1;userb\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_user_v1_user_proto_goTypes = []any{
	(*User)(nil),                     // 0: user.v1.User
	(*PublicProfile)(nil),            // 1: user.v1.PublicProfile
	(*PortfolioItem)(nil),            // 2: user.v1.PortfolioItem
	(*CreateUserRequest)(nil),        // 3: user.v1.CreateUserRequest
	(*CreateUserResponse)(nil),       // 4: user.v1.CreateUserResponse
	(*UpdateUserRequest)(nil),        // 5: user.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),       // 6: user.v1.UpdateUserResponse
	(*LoginRequest)(nil),             // 7: user.v1.LoginRequest
	(*LoginResponse)(nil),            // 8: user.v1.LoginResponse
	(*LogoutRequest)(nil),            // 9: user.v1.LogoutRequest
	(*LogoutResponse)(nil),           // 10: user.v1.LogoutResponse
	(*GetMeRequest)(nil),             // 11: user.v1.GetMeRequest
	(*GetMeResponse)(nil),            // 12: user.v1.GetMeResponse
	(*GetPublicProfileRequest)(nil),  // 13: user.v1.GetPublicProfileRequest
	(*GetPublicProfileResponse)(nil), // 14: user.v1.GetPublicProfileResponse
	nil,                              // 15: user.v1.User.PortfolioEntry
	nil,                              // 16: user.v1.PublicProfile.PortfolioEntry
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),    // 18: google.protobuf.FieldMask
}
var file_user_v1_user_proto_depIdxs = []int32{
	17, // 0: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: user.v1.User.portfolio:type_name -> user.v1.User.PortfolioEntry
	16, // 2: user.v1.PublicProfile.portfolio:type_name -> user.v1.PublicProfile.PortfolioEntry
	0,  // 3: user.v1.CreateUserResponse.user:type_name -> user.v1.User
	18, // 4: user.v1.UpdateUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 5: user.v1.UpdateUserResponse.user:type_name -> user.v1.User
	0,  // 6: user.v1.LoginResponse.user:type_name -> user.v1.User
	0,  // 7: user.v1.GetMeResponse.user:type_name -> user.v1.User
	1,  // 8: user.v1.GetPublicProfileResponse.profile:type_name -> user.v1.PublicProfile
	2,  // 9: user.v1.User.PortfolioEntry.value:type_name -> user.v1.PortfolioItem
	2,  // 10: user.v1.PublicProfile.PortfolioEntry.value:type_name -> user.v1.PortfolioItem
	3,  // 11: user.v1.UserService.CreateUser:input_type -> user.v1.CreateUserRequest
	7,  // 12: user.v1.UserService.Login:input_type -> user.v1.LoginRequest
	9,  // 13: user.v1.UserService.Logout:input_type -> user.v1.LogoutRequest
	11, // 14: user.v1.UserService.GetMe:input_type -> user.v1.GetMeRequest
	5,  // 15: user.v1.UserService.UpdateUser:input_type -> user.v1.UpdateUserRequest
	13, // 16: user.v1.UserService.GetPublicProfile:input_type -> user.v1.GetPublicProfileRequest
	4,  // 17: user.v1.UserService.CreateUser:output_type -> user.v1.CreateUserResponse
	8,  // 18: user.v1.UserService.Login:output_type -> user.v1.LoginResponse
	10, // 19: user.v1.UserService.Logout:output_type -> user.v1.LogoutResponse
	12, // 20: user.v1.UserService.GetMe:output_type -> user.v1.GetMeResponse
	6,  // 21: user.v1.UserService.UpdateUser:output_type -> user.v1.UpdateUserResponse
	14, // 22: user.v1.UserService.GetPublicProfile:output_type -> user.v1.GetPublicProfileResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
