// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: leaderboard/v1/leaderboard.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { User } from "../../user/v1/user";

export const protobufPackage = "leaderboard.v1";

export interface LeaderboardEntry {
  user: User | undefined;
  rank: number;
  score: number;
}

export interface GetLeaderboardRequest {
  limit: number;
  offset: number;
}

export interface GetLeaderboardResponse {
  entries: LeaderboardEntry[];
  total_count: number;
  last_update: string;
}

function createBaseLeaderboardEntry(): LeaderboardEntry {
  return { user: undefined, rank: 0, score: 0 };
}

export const LeaderboardEntry: MessageFns<LeaderboardEntry> = {
  encode(message: LeaderboardEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(10).fork()).join();
    }
    if (message.rank !== 0) {
      writer.uint32(16).int32(message.rank);
    }
    if (message.score !== 0) {
      writer.uint32(25).double(message.score);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LeaderboardEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLeaderboardEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.rank = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.score = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LeaderboardEntry {
    return {
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
      rank: isSet(object.rank) ? globalThis.Number(object.rank) : 0,
      score: isSet(object.score) ? globalThis.Number(object.score) : 0,
    };
  },

  toJSON(message: LeaderboardEntry): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    if (message.rank !== 0) {
      obj.rank = Math.round(message.rank);
    }
    if (message.score !== 0) {
      obj.score = message.score;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LeaderboardEntry>, I>>(base?: I): LeaderboardEntry {
    return LeaderboardEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LeaderboardEntry>, I>>(object: I): LeaderboardEntry {
    const message = createBaseLeaderboardEntry();
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    message.rank = object.rank ?? 0;
    message.score = object.score ?? 0;
    return message;
  },
};

function createBaseGetLeaderboardRequest(): GetLeaderboardRequest {
  return { limit: 0, offset: 0 };
}

export const GetLeaderboardRequest: MessageFns<GetLeaderboardRequest> = {
  encode(message: GetLeaderboardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.limit !== 0) {
      writer.uint32(8).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(16).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLeaderboardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLeaderboardRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetLeaderboardRequest {
    return {
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: GetLeaderboardRequest): unknown {
    const obj: any = {};
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetLeaderboardRequest>, I>>(base?: I): GetLeaderboardRequest {
    return GetLeaderboardRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetLeaderboardRequest>, I>>(object: I): GetLeaderboardRequest {
    const message = createBaseGetLeaderboardRequest();
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseGetLeaderboardResponse(): GetLeaderboardResponse {
  return { entries: [], total_count: 0, last_update: "0" };
}

export const GetLeaderboardResponse: MessageFns<GetLeaderboardResponse> = {
  encode(message: GetLeaderboardResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entries) {
      LeaderboardEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total_count !== 0) {
      writer.uint32(16).int32(message.total_count);
    }
    if (message.last_update !== "0") {
      writer.uint32(24).int64(message.last_update);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLeaderboardResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLeaderboardResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entries.push(LeaderboardEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total_count = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.last_update = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetLeaderboardResponse {
    return {
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => LeaderboardEntry.fromJSON(e))
        : [],
      total_count: isSet(object.totalCount)
        ? globalThis.Number(object.totalCount)
        : isSet(object.total_count)
        ? globalThis.Number(object.total_count)
        : 0,
      last_update: isSet(object.lastUpdate)
        ? globalThis.String(object.lastUpdate)
        : isSet(object.last_update)
        ? globalThis.String(object.last_update)
        : "0",
    };
  },

  toJSON(message: GetLeaderboardResponse): unknown {
    const obj: any = {};
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => LeaderboardEntry.toJSON(e));
    }
    if (message.total_count !== 0) {
      obj.totalCount = Math.round(message.total_count);
    }
    if (message.last_update !== "0") {
      obj.lastUpdate = message.last_update;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetLeaderboardResponse>, I>>(base?: I): GetLeaderboardResponse {
    return GetLeaderboardResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetLeaderboardResponse>, I>>(object: I): GetLeaderboardResponse {
    const message = createBaseGetLeaderboardResponse();
    message.entries = object.entries?.map((e) => LeaderboardEntry.fromPartial(e)) || [];
    message.total_count = object.total_count ?? 0;
    message.last_update = object.last_update ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
