// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: portfolio/v1/portfolio.proto

package portfolio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortfolioItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockSymbol   string                 `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AveragePrice  float64                `protobuf:"fixed64,3,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioItem) Reset() {
	*x = PortfolioItem{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioItem) ProtoMessage() {}

func (x *PortfolioItem) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioItem.ProtoReflect.Descriptor instead.
func (*PortfolioItem) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{0}
}

func (x *PortfolioItem) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *PortfolioItem) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PortfolioItem) GetAveragePrice() float64 {
	if x != nil {
		return x.AveragePrice
	}
	return 0
}

var File_portfolio_v1_portfolio_proto protoreflect.FileDescriptor

const file_portfolio_v1_portfolio_proto_rawDesc = "" +
	"\n" +
	"\x1cportfolio/v1/portfolio.proto\x12\fportfolio.v1\"s\n" +
	"\rPortfolioItem\x12!\n" +
	"\fstock_symbol\x18\x01 \x01(\tR\vstockSymbol\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12#\n" +
	"\raverage_price\x18\x03 \x01(\x01R\faveragePriceBRZPgithub.com/tmythicator/ticker-rush/backend/internal/proto/portfolio/v1;portfoliob\x06proto3"

var (
	file_portfolio_v1_portfolio_proto_rawDescOnce sync.Once
	file_portfolio_v1_portfolio_proto_rawDescData []byte
)

func file_portfolio_v1_portfolio_proto_rawDescGZIP() []byte {
	file_portfolio_v1_portfolio_proto_rawDescOnce.Do(func() {
		file_portfolio_v1_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portfolio_v1_portfolio_proto_rawDesc), len(file_portfolio_v1_portfolio_proto_rawDesc)))
	})
	return file_portfolio_v1_portfolio_proto_rawDescData
}

var file_portfolio_v1_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_portfolio_v1_portfolio_proto_goTypes = []any{
	(*PortfolioItem)(nil), // 0: portfolio.v1.PortfolioItem
}
var file_portfolio_v1_portfolio_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_portfolio_v1_portfolio_proto_init() }
func file_portfolio_v1_portfolio_proto_init() {
	if File_portfolio_v1_portfolio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portfolio_v1_portfolio_proto_rawDesc), len(file_portfolio_v1_portfolio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_portfolio_v1_portfolio_proto_goTypes,
		DependencyIndexes: file_portfolio_v1_portfolio_proto_depIdxs,
		MessageInfos:      file_portfolio_v1_portfolio_proto_msgTypes,
	}.Build()
	File_portfolio_v1_portfolio_proto = out.File
	file_portfolio_v1_portfolio_proto_goTypes = nil
	file_portfolio_v1_portfolio_proto_depIdxs = nil
}
