version: "0.5"

processes:
  valkey:
    command: task run:valkey
    availability:
      restart: always

  postgres:
    command: task run:postgres
    availability:
      restart: always
    readiness_probe:
      exec:
        command: pg_isready -h ${POSTGRES_HOST:-localhost} -p ${POSTGRES_PORT:-5432} -U ${POSTGRES_USER:-postgres}
    shutdown:
      signal: 2

  exchange:
    command: task run:exchange

    depends_on:
      valkey:
        condition: process_started
      postgres:
        condition: process_healthy

  fetcher:
    command: task run:fetcher

    depends_on:
      valkey:
        condition: process_started

  frontend:
    command: task run:frontend
