version: "0.5"

processes:
  valkey:
    command: valkey-server --port ${REDIS_PORT:-6379}
    availability:
      restart: always

  postgres:
    command: postgres -p ${POSTGRES_PORT:-5432}
    availability:
      restart: always
    readiness_probe:
      exec:
        command: pg_isready -h ${POSTGRES_HOST:-localhost} -p ${POSTGRES_PORT:-5432} -U ${POSTGRES_USER:-postgres}

  exchange:
    command: |
      cd backend
      # Wait for Valkey
      sleep 1
      go run ./cmd/exchange

    depends_on:
      valkey:
        condition: process_started
      postgres:
        condition: process_healthy

  fetcher:
    command: |
      cd backend
      # Wait for Valkey
      sleep 1
      go run ./cmd/fetcher

    depends_on:
      valkey:
        condition: process_started

  frontend:
    command: |
      cd frontend
      pnpm install
      pnpm run dev
