version: "0.5"

processes:
  valkey:
    command: task valkey:run

  postgres:
    command: task postgres:run
    readiness_probe:
      exec:
        command: pg_isready -h "$PGDATA"

  exchange:
    command: task postgres:create && task backend:run:exchange
    depends_on:
      postgres:
        condition: process_healthy

  fetcher:
    command: task backend:run:fetcher

  frontend:
    command: task frontend:run

  bot:
    command: task bot:run
