version: '3'

dotenv: ['.env']

tasks:
  dev:
    desc: Start the development environment
    cmds:
      - process-compose up

  deps:
    desc: Install all dependencies
    cmds:
      - task: backend:deps
      - task: frontend:deps

  test:
    desc: Run all tests
    cmds:
      - task: backend:test
      - task: frontend:test

  lint:
    desc: Lint all code
    cmds:
      - task: backend:lint
      - task: frontend:lint

  build:
    desc: Build everything
    cmds:
      - task: backend:build
      - task: frontend:build

  backend:deps:
    desc: Install backend dependencies
    dir: backend
    cmds:
      - go mod download

  generate:
    desc: Generate code using Buf
    cmds:
      - buf generate
      - task: backend:sqlc

  backend:sqlc:
    desc: Generate code from SQL
    dir: backend
    cmds:
      - sqlc generate

  backend:build:
    desc: Build the backend services
    dir: backend
    cmds:
      - go build -o exchange cmd/exchange/main.go
      - go build -o fetcher cmd/fetcher/main.go

  backend:test:
    desc: Run backend tests
    dir: backend
    cmds:
      - go test -v ./...

  backend:lint:
    desc: Lint backend code
    dir: backend
    cmds:
      - golangci-lint run

  backend:run:exchange:
    desc: Run the exchange service
    dir: backend
    cmds:
      - go run cmd/exchange/main.go
    env:
      PORT: '{{.SERVER_PORT | default "8081"}}'

  backend:run:fetcher:
    desc: Run the fetcher service
    dir: backend
    cmds:
      - go run cmd/fetcher/main.go

  frontend:deps:
    desc: Install frontend dependencies
    dir: frontend
    cmds:
      - pnpm install --frozen-lockfile

  frontend:test:
    desc: Run frontend tests
    dir: frontend
    cmds:
      - pnpm test

  frontend:lint:
    desc: Lint frontend code
    dir: frontend
    cmds:
      - pnpm lint
      - pnpm tsc --noEmit

  frontend:build:
    desc: Build frontend
    dir: frontend
    cmds:
      - pnpm build

  frontend:run:
    desc: Run the frontend
    dir: frontend
    cmds:
      - pnpm install
      - pnpm run dev
    env:
      PORT: '{{.CLIENT_PORT | default "8080"}}'

  postgres:run:
    desc: Run Postgres
    cmds:
      - postgres -p {{.POSTGRES_PORT | default "5432"}}

  postgres:reset:
    desc: Reset the database (Drop, Create)
    dir: backend
    cmds:
      - dropdb -h {{.POSTGRES_HOST | default "localhost"}} -p {{.POSTGRES_PORT | default "5432"}} -U {{.POSTGRES_USER | default "postgres"}} {{.POSTGRES_DB | default "ticker_rush"}} --if-exists
      - createdb -h {{.POSTGRES_HOST | default "localhost"}} -p {{.POSTGRES_PORT | default "5432"}} -U {{.POSTGRES_USER | default "postgres"}} {{.POSTGRES_DB | default "ticker_rush"}}

  valkey:run:
    desc: Run Valkey (Redis)
    cmds:
      - valkey-server --port {{.REDIS_PORT | default "6379"}}
