version: '3'

dotenv: ['.env']

tasks:
  generate:
    desc: Generate code from SQL and Protobuf
    dir: backend
    cmds:
      - sqlc generate
      - protoc --go_out=. --go_opt=paths=source_relative proto/user/*.proto

  migrate:
    desc: Run database migrations
    dir: backend
    cmds:
      - createdb -h {{.POSTGRES_HOST | default "localhost"}} -p {{.POSTGRES_PORT | default "5432"}} -U {{.POSTGRES_USER | default "postgres"}} {{.POSTGRES_DB | default "ticker_rush"}} || true
      - goose -dir db/migrations up
    env:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: 'postgres://{{.POSTGRES_USER | default "postgres"}}:{{.POSTGRES_PASSWORD}}@{{.POSTGRES_HOST | default "localhost"}}:{{.POSTGRES_PORT | default "5432"}}/{{.POSTGRES_DB | default "ticker_rush"}}?sslmode=disable'

  deps:
    desc: Install all dependencies
    cmds:
      - task: deps:backend
      - task: deps:frontend

  deps:backend:
    desc: Install backend dependencies
    dir: backend
    cmds:
      - go mod download

  deps:frontend:
    desc: Install frontend dependencies
    dir: frontend
    cmds:
      - pnpm install --frozen-lockfile

  build:
    desc: Build the backend services
    dir: backend
    cmds:
      - go build -o exchange cmd/exchange/main.go
      - go build -o fetcher cmd/fetcher/main.go

  test:
    desc: Run all tests
    cmds:
      - task: test:backend
      - task: test:frontend

  test:backend:
    desc: Run backend tests
    dir: backend
    cmds:
      - go test -v ./...

  test:frontend:
    desc: Run frontend tests
    dir: frontend
    cmds:
      - pnpm test

  dev:
    desc: Start the development environment
    cmds:
      - process-compose up

  run:exchange:
    desc: Run the exchange service
    dir: backend
    cmds:
      - go run cmd/exchange/main.go
    env:
      PORT: '{{.SERVER_PORT | default "8081"}}'

  run:fetcher:
    desc: Run the fetcher service
    dir: backend
    cmds:
      - go run cmd/fetcher/main.go

  run:frontend:
    desc: Run the frontend
    dir: frontend
    cmds:
      - pnpm install
      - pnpm run dev
    env:
      PORT: '{{.CLIENT_PORT | default "8080"}}'

  run:valkey:
    desc: Run Valkey (Redis)
    cmds:
      - valkey-server --port {{.REDIS_PORT | default "6379"}}

  run:postgres:
    desc: Run Postgres
    cmds:
      - postgres -p {{.POSTGRES_PORT | default "5432"}}
