version: "2"
run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes: github.com/tmythicator/ticker-rush/backend

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocyclo
    - revive
    - nlreturn
  settings:
    govet:
      enable:
        - nilness
        - shadow
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          disabled: false
        - name: blank-imports
          disabled: false
        - name: context-as-argument
          disabled: false
        - name: error-naming
          disabled: false
        - name: error-return
          disabled: false
        - name: error-strings
          disabled: false
        - name: if-return
          disabled: false
        - name: increment-decrement
          disabled: false
        - name: var-naming
          disabled: false
        - name: var-declaration
          disabled: false
        - name: package-comments
          disabled: false
        - name: range
          disabled: false
        - name: receiver-naming
          disabled: false
        - name: time-naming
          disabled: false
        - name: unexported-return
          disabled: false
        - name: indent-error-flow
          disabled: false
        - name: errorf
          disabled: false
