# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/user.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'user/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuser/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n\rPortfolioItem\x12!\n\x0cstock_symbol\x18\x01 \x01(\tR\x0bstockSymbol\x12\x1a\n\x08quantity\x18\x02 \x01(\x01R\x08quantity\x12#\n\raverage_price\x18\x03 \x01(\x01R\x0c\x61veragePrice\"\xee\x02\n\x04User\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n\x05\x65mail\x18\x02 \x01(\tR\x05\x65mail\x12#\n\rpassword_hash\x18\x03 \x01(\tR\x0cpasswordHash\x12\x18\n\x07\x62\x61lance\x18\x04 \x01(\x01R\x07\x62\x61lance\x12\x39\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n\nfirst_name\x18\x07 \x01(\tR\tfirstName\x12\x1b\n\tlast_name\x18\x08 \x01(\tR\x08lastName\x12\x37\n\tportfolio\x18\t \x03(\x0b\x32\x19.user.User.PortfolioEntryR\tportfolio\x1aQ\n\x0ePortfolioEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x13.user.PortfolioItemR\x05value:\x02\x38\x01\x42?Z=github.com/tmythicator/ticker-rush/server/internal/proto/userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/tmythicator/ticker-rush/server/internal/proto/user'
  _globals['_USER_PORTFOLIOENTRY']._loaded_options = None
  _globals['_USER_PORTFOLIOENTRY']._serialized_options = b'8\001'
  _globals['_PORTFOLIOITEM']._serialized_start=58
  _globals['_PORTFOLIOITEM']._serialized_end=173
  _globals['_USER']._serialized_start=176
  _globals['_USER']._serialized_end=542
  _globals['_USER_PORTFOLIOENTRY']._serialized_start=461
  _globals['_USER_PORTFOLIOENTRY']._serialized_end=542
# @@protoc_insertion_point(module_scope)
