// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: leaderboard/v1/leaderboard.proto

package leaderboard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaderBoardService_GetLeaderboard_FullMethodName = "/leaderboard.v1.LeaderBoardService/GetLeaderboard"
)

// LeaderBoardServiceClient is the client API for LeaderBoardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaderBoardServiceClient interface {
	GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error)
}

type leaderBoardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderBoardServiceClient(cc grpc.ClientConnInterface) LeaderBoardServiceClient {
	return &leaderBoardServiceClient{cc}
}

func (c *leaderBoardServiceClient) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderboardResponse)
	err := c.cc.Invoke(ctx, LeaderBoardService_GetLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderBoardServiceServer is the server API for LeaderBoardService service.
// All implementations must embed UnimplementedLeaderBoardServiceServer
// for forward compatibility.
type LeaderBoardServiceServer interface {
	GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error)
	mustEmbedUnimplementedLeaderBoardServiceServer()
}

// UnimplementedLeaderBoardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaderBoardServiceServer struct{}

func (UnimplementedLeaderBoardServiceServer) GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedLeaderBoardServiceServer) mustEmbedUnimplementedLeaderBoardServiceServer() {}
func (UnimplementedLeaderBoardServiceServer) testEmbeddedByValue()                            {}

// UnsafeLeaderBoardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderBoardServiceServer will
// result in compilation errors.
type UnsafeLeaderBoardServiceServer interface {
	mustEmbedUnimplementedLeaderBoardServiceServer()
}

func RegisterLeaderBoardServiceServer(s grpc.ServiceRegistrar, srv LeaderBoardServiceServer) {
	// If the following call pancis, it indicates UnimplementedLeaderBoardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaderBoardService_ServiceDesc, srv)
}

func _LeaderBoardService_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderBoardServiceServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderBoardService_GetLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderBoardServiceServer).GetLeaderboard(ctx, req.(*GetLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaderBoardService_ServiceDesc is the grpc.ServiceDesc for LeaderBoardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderBoardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leaderboard.v1.LeaderBoardService",
	HandlerType: (*LeaderBoardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLeaderboard",
			Handler:    _LeaderBoardService_GetLeaderboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leaderboard/v1/leaderboard.proto",
}
