// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: leaderboard/v1/leaderboard.proto

package leaderboard

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/tmythicator/ticker-rush/backend/internal/proto/user/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Single participant standing on the leaderboard.
type LeaderboardEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User profile of the participant.
	User *v1.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Current rank standing.
	Rank int32 `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	// Current score or net worth value.
	Score         float64 `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderboardEntry) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// Request to fetch the leaderboard.
type GetLeaderboardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of entries to return.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset.
	Offset        int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLeaderboardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Response containing the leaderboard standings.
type GetLeaderboardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ranked leaderboard entries.
	Entries []*LeaderboardEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Total number of participants.
	TotalCount int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Unix timestamp of the last cache update in seconds.
	LastUpdate    int64 `protobuf:"varint,3,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetLeaderboardResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetLeaderboardResponse) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

var File_leaderboard_v1_leaderboard_proto protoreflect.FileDescriptor

const file_leaderboard_v1_leaderboard_proto_rawDesc = "" +
	"\n" +
	" leaderboard/v1/leaderboard.proto\x12\x0eleaderboard.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x12user/v1/user.proto\"_\n" +
	"\x10LeaderboardEntry\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\"E\n" +
	"\x15GetLeaderboardRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x96\x01\n" +
	"\x16GetLeaderboardResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .leaderboard.v1.LeaderboardEntryR\aentries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vlast_update\x18\x03 \x01(\x03R\n" +
	"lastUpdate2\x8f\x01\n" +
	"\x12LeaderBoardService\x12y\n" +
	"\x0eGetLeaderboard\x12%.leaderboard.v1.GetLeaderboardRequest\x1a&.leaderboard.v1.GetLeaderboardResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/leaderboardB\xb5\x01\x92A\\\x12Z\n" +
	"\x17Leaderboard Service API\x128API for retrieving paginated player standings and ranks.2\x051.0.0ZTgithub.com/tmythicator/ticker-rush/backend/internal/proto/leaderboard/v1;leaderboardb\x06proto3"

var (
	file_leaderboard_v1_leaderboard_proto_rawDescOnce sync.Once
	file_leaderboard_v1_leaderboard_proto_rawDescData []byte
)

func file_leaderboard_v1_leaderboard_proto_rawDescGZIP() []byte {
	file_leaderboard_v1_leaderboard_proto_rawDescOnce.Do(func() {
		file_leaderboard_v1_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaderboard_v1_leaderboard_proto_rawDesc), len(file_leaderboard_v1_leaderboard_proto_rawDesc)))
	})
	return file_leaderboard_v1_leaderboard_proto_rawDescData
}

var file_leaderboard_v1_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_leaderboard_v1_leaderboard_proto_goTypes = []any{
	(*LeaderboardEntry)(nil),       // 0: leaderboard.v1.LeaderboardEntry
	(*GetLeaderboardRequest)(nil),  // 1: leaderboard.v1.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil), // 2: leaderboard.v1.GetLeaderboardResponse
	(*v1.User)(nil),                // 3: user.v1.User
}
var file_leaderboard_v1_leaderboard_proto_depIdxs = []int32{
	3, // 0: leaderboard.v1.LeaderboardEntry.user:type_name -> user.v1.User
	0, // 1: leaderboard.v1.GetLeaderboardResponse.entries:type_name -> leaderboard.v1.LeaderboardEntry
	1, // 2: leaderboard.v1.LeaderBoardService.GetLeaderboard:input_type -> leaderboard.v1.GetLeaderboardRequest
	2, // 3: leaderboard.v1.LeaderBoardService.GetLeaderboard:output_type -> leaderboard.v1.GetLeaderboardResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_leaderboard_v1_leaderboard_proto_init() }
func file_leaderboard_v1_leaderboard_proto_init() {
	if File_leaderboard_v1_leaderboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaderboard_v1_leaderboard_proto_rawDesc), len(file_leaderboard_v1_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaderboard_v1_leaderboard_proto_goTypes,
		DependencyIndexes: file_leaderboard_v1_leaderboard_proto_depIdxs,
		MessageInfos:      file_leaderboard_v1_leaderboard_proto_msgTypes,
	}.Build()
	File_leaderboard_v1_leaderboard_proto = out.File
	file_leaderboard_v1_leaderboard_proto_goTypes = nil
	file_leaderboard_v1_leaderboard_proto_depIdxs = nil
}
