// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: leaderboard/v1/leaderboard.proto

package leaderboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	TotalNetWorth float64                `protobuf:"fixed64,3,opt,name=total_net_worth,json=totalNetWorth,proto3" json:"total_net_worth,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	IsPublic      bool                   `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderboardEntry) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetTotalNetWorth() float64 {
	if x != nil {
		return x.TotalNetWorth
	}
	return 0
}

func (x *LeaderboardEntry) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *LeaderboardEntry) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *LeaderboardEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LeaderboardEntry) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLeaderboardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	LastUpdate    int64                  `protobuf:"varint,3,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetLeaderboardResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetLeaderboardResponse) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

var File_leaderboard_v1_leaderboard_proto protoreflect.FileDescriptor

const file_leaderboard_v1_leaderboard_proto_rawDesc = "" +
	"\n" +
	" leaderboard/v1/leaderboard.proto\x12\x0eleaderboard.v1\"\xdc\x01\n" +
	"\x10LeaderboardEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12&\n" +
	"\x0ftotal_net_worth\x18\x03 \x01(\x01R\rtotalNetWorth\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1b\n" +
	"\tis_public\x18\a \x01(\bR\bisPublic\"E\n" +
	"\x15GetLeaderboardRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x96\x01\n" +
	"\x16GetLeaderboardResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .leaderboard.v1.LeaderboardEntryR\aentries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vlast_update\x18\x03 \x01(\x03R\n" +
	"lastUpdate2u\n" +
	"\x12LeaderBoardService\x12_\n" +
	"\x0eGetLeaderboard\x12%.leaderboard.v1.GetLeaderboardRequest\x1a&.leaderboard.v1.GetLeaderboardResponseBUZSgithub.com/tmythicator/ticker-rush/server/internal/proto/leaderboard/v1;leaderboardb\x06proto3"

var (
	file_leaderboard_v1_leaderboard_proto_rawDescOnce sync.Once
	file_leaderboard_v1_leaderboard_proto_rawDescData []byte
)

func file_leaderboard_v1_leaderboard_proto_rawDescGZIP() []byte {
	file_leaderboard_v1_leaderboard_proto_rawDescOnce.Do(func() {
		file_leaderboard_v1_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaderboard_v1_leaderboard_proto_rawDesc), len(file_leaderboard_v1_leaderboard_proto_rawDesc)))
	})
	return file_leaderboard_v1_leaderboard_proto_rawDescData
}

var file_leaderboard_v1_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_leaderboard_v1_leaderboard_proto_goTypes = []any{
	(*LeaderboardEntry)(nil),       // 0: leaderboard.v1.LeaderboardEntry
	(*GetLeaderboardRequest)(nil),  // 1: leaderboard.v1.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil), // 2: leaderboard.v1.GetLeaderboardResponse
}
var file_leaderboard_v1_leaderboard_proto_depIdxs = []int32{
	0, // 0: leaderboard.v1.GetLeaderboardResponse.entries:type_name -> leaderboard.v1.LeaderboardEntry
	1, // 1: leaderboard.v1.LeaderBoardService.GetLeaderboard:input_type -> leaderboard.v1.GetLeaderboardRequest
	2, // 2: leaderboard.v1.LeaderBoardService.GetLeaderboard:output_type -> leaderboard.v1.GetLeaderboardResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_leaderboard_v1_leaderboard_proto_init() }
func file_leaderboard_v1_leaderboard_proto_init() {
	if File_leaderboard_v1_leaderboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaderboard_v1_leaderboard_proto_rawDesc), len(file_leaderboard_v1_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaderboard_v1_leaderboard_proto_goTypes,
		DependencyIndexes: file_leaderboard_v1_leaderboard_proto_depIdxs,
		MessageInfos:      file_leaderboard_v1_leaderboard_proto_msgTypes,
	}.Build()
	File_leaderboard_v1_leaderboard_proto = out.File
	file_leaderboard_v1_leaderboard_proto_goTypes = nil
	file_leaderboard_v1_leaderboard_proto_depIdxs = nil
}
