// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: porfolio/v1/porfolio.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "portfolio.v1";

export interface PortfolioItem {
  stock_symbol: string;
  quantity: number;
  average_price: number;
}

function createBasePortfolioItem(): PortfolioItem {
  return { stock_symbol: "", quantity: 0, average_price: 0 };
}

export const PortfolioItem: MessageFns<PortfolioItem> = {
  encode(message: PortfolioItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stock_symbol !== "") {
      writer.uint32(10).string(message.stock_symbol);
    }
    if (message.quantity !== 0) {
      writer.uint32(17).double(message.quantity);
    }
    if (message.average_price !== 0) {
      writer.uint32(25).double(message.average_price);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PortfolioItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePortfolioItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stock_symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.quantity = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.average_price = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PortfolioItem {
    return {
      stock_symbol: isSet(object.stockSymbol)
        ? globalThis.String(object.stockSymbol)
        : isSet(object.stock_symbol)
        ? globalThis.String(object.stock_symbol)
        : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      average_price: isSet(object.averagePrice)
        ? globalThis.Number(object.averagePrice)
        : isSet(object.average_price)
        ? globalThis.Number(object.average_price)
        : 0,
    };
  },

  toJSON(message: PortfolioItem): unknown {
    const obj: any = {};
    if (message.stock_symbol !== "") {
      obj.stockSymbol = message.stock_symbol;
    }
    if (message.quantity !== 0) {
      obj.quantity = message.quantity;
    }
    if (message.average_price !== 0) {
      obj.averagePrice = message.average_price;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PortfolioItem>, I>>(base?: I): PortfolioItem {
    return PortfolioItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PortfolioItem>, I>>(object: I): PortfolioItem {
    const message = createBasePortfolioItem();
    message.stock_symbol = object.stock_symbol ?? "";
    message.quantity = object.quantity ?? 0;
    message.average_price = object.average_price ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
