// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: ladder/v1/ladder.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../../google/protobuf/timestamp";
import { User } from "../../user/v1/user";

export const protobufPackage = "ladder.v1";

/** Ladder represents a competition cycle. */
export interface Ladder {
  id: string;
  name: string;
  type: string;
  start_time: Date | undefined;
  end_time: Date | undefined;
  is_active: boolean;
  created_at: Date | undefined;
  initial_balance: number;
  allowed_tickers: TickerInfo[];
}

export interface TickerInfo {
  symbol: string;
  source: string;
}

/** LadderParticipant represents a user's standing in a ladder. */
export interface LadderParticipant {
  ladder_id: string;
  user: User | undefined;
  final_rank: number;
  joined_at: Date | undefined;
}

export interface LadderLeaderboardEntry {
  participant: LadderParticipant | undefined;
}

export interface ListLaddersRequest {
}

export interface ListLaddersResponse {
  ladders: Ladder[];
}

export interface GetActiveLadderRequest {
}

export interface GetActiveLadderResponse {
  ladder: Ladder | undefined;
}

export interface GetLadderLeaderboardRequest {
  ladder_id: string;
  limit: number;
}

export interface GetLadderLeaderboardResponse {
  entries: LadderLeaderboardEntry[];
}

export interface GetMyLadderStatsRequest {
  ladder_id: string;
}

export interface GetMyLadderStatsResponse {
  participant: LadderParticipant | undefined;
}

function createBaseLadder(): Ladder {
  return {
    id: "0",
    name: "",
    type: "",
    start_time: undefined,
    end_time: undefined,
    is_active: false,
    created_at: undefined,
    initial_balance: 0,
    allowed_tickers: [],
  };
}

export const Ladder: MessageFns<Ladder> = {
  encode(message: Ladder, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "0") {
      writer.uint32(8).int64(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.type !== "") {
      writer.uint32(26).string(message.type);
    }
    if (message.start_time !== undefined) {
      Timestamp.encode(toTimestamp(message.start_time), writer.uint32(34).fork()).join();
    }
    if (message.end_time !== undefined) {
      Timestamp.encode(toTimestamp(message.end_time), writer.uint32(42).fork()).join();
    }
    if (message.is_active !== false) {
      writer.uint32(48).bool(message.is_active);
    }
    if (message.created_at !== undefined) {
      Timestamp.encode(toTimestamp(message.created_at), writer.uint32(58).fork()).join();
    }
    if (message.initial_balance !== 0) {
      writer.uint32(65).double(message.initial_balance);
    }
    for (const v of message.allowed_tickers) {
      TickerInfo.encode(v!, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Ladder {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLadder();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.start_time = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.end_time = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.is_active = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.created_at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.initial_balance = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.allowed_tickers.push(TickerInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Ladder {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "0",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      start_time: isSet(object.startTime)
        ? fromJsonTimestamp(object.startTime)
        : isSet(object.start_time)
        ? fromJsonTimestamp(object.start_time)
        : undefined,
      end_time: isSet(object.endTime)
        ? fromJsonTimestamp(object.endTime)
        : isSet(object.end_time)
        ? fromJsonTimestamp(object.end_time)
        : undefined,
      is_active: isSet(object.isActive)
        ? globalThis.Boolean(object.isActive)
        : isSet(object.is_active)
        ? globalThis.Boolean(object.is_active)
        : false,
      created_at: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
        ? fromJsonTimestamp(object.created_at)
        : undefined,
      initial_balance: isSet(object.initialBalance)
        ? globalThis.Number(object.initialBalance)
        : isSet(object.initial_balance)
        ? globalThis.Number(object.initial_balance)
        : 0,
      allowed_tickers: globalThis.Array.isArray(object?.allowedTickers)
        ? object.allowedTickers.map((e: any) => TickerInfo.fromJSON(e))
        : globalThis.Array.isArray(object?.allowed_tickers)
        ? object.allowed_tickers.map((e: any) => TickerInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Ladder): unknown {
    const obj: any = {};
    if (message.id !== "0") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.start_time !== undefined) {
      obj.startTime = message.start_time.toISOString();
    }
    if (message.end_time !== undefined) {
      obj.endTime = message.end_time.toISOString();
    }
    if (message.is_active !== false) {
      obj.isActive = message.is_active;
    }
    if (message.created_at !== undefined) {
      obj.createdAt = message.created_at.toISOString();
    }
    if (message.initial_balance !== 0) {
      obj.initialBalance = message.initial_balance;
    }
    if (message.allowed_tickers?.length) {
      obj.allowedTickers = message.allowed_tickers.map((e) => TickerInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ladder>, I>>(base?: I): Ladder {
    return Ladder.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ladder>, I>>(object: I): Ladder {
    const message = createBaseLadder();
    message.id = object.id ?? "0";
    message.name = object.name ?? "";
    message.type = object.type ?? "";
    message.start_time = object.start_time ?? undefined;
    message.end_time = object.end_time ?? undefined;
    message.is_active = object.is_active ?? false;
    message.created_at = object.created_at ?? undefined;
    message.initial_balance = object.initial_balance ?? 0;
    message.allowed_tickers = object.allowed_tickers?.map((e) => TickerInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTickerInfo(): TickerInfo {
  return { symbol: "", source: "" };
}

export const TickerInfo: MessageFns<TickerInfo> = {
  encode(message: TickerInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.source !== "") {
      writer.uint32(18).string(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TickerInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTickerInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.source = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TickerInfo {
    return {
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      source: isSet(object.source) ? globalThis.String(object.source) : "",
    };
  },

  toJSON(message: TickerInfo): unknown {
    const obj: any = {};
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.source !== "") {
      obj.source = message.source;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TickerInfo>, I>>(base?: I): TickerInfo {
    return TickerInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TickerInfo>, I>>(object: I): TickerInfo {
    const message = createBaseTickerInfo();
    message.symbol = object.symbol ?? "";
    message.source = object.source ?? "";
    return message;
  },
};

function createBaseLadderParticipant(): LadderParticipant {
  return { ladder_id: "0", user: undefined, final_rank: 0, joined_at: undefined };
}

export const LadderParticipant: MessageFns<LadderParticipant> = {
  encode(message: LadderParticipant, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ladder_id !== "0") {
      writer.uint32(8).int64(message.ladder_id);
    }
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(18).fork()).join();
    }
    if (message.final_rank !== 0) {
      writer.uint32(24).int32(message.final_rank);
    }
    if (message.joined_at !== undefined) {
      Timestamp.encode(toTimestamp(message.joined_at), writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LadderParticipant {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLadderParticipant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ladder_id = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.final_rank = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.joined_at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LadderParticipant {
    return {
      ladder_id: isSet(object.ladderId)
        ? globalThis.String(object.ladderId)
        : isSet(object.ladder_id)
        ? globalThis.String(object.ladder_id)
        : "0",
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
      final_rank: isSet(object.finalRank)
        ? globalThis.Number(object.finalRank)
        : isSet(object.final_rank)
        ? globalThis.Number(object.final_rank)
        : 0,
      joined_at: isSet(object.joinedAt)
        ? fromJsonTimestamp(object.joinedAt)
        : isSet(object.joined_at)
        ? fromJsonTimestamp(object.joined_at)
        : undefined,
    };
  },

  toJSON(message: LadderParticipant): unknown {
    const obj: any = {};
    if (message.ladder_id !== "0") {
      obj.ladderId = message.ladder_id;
    }
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    if (message.final_rank !== 0) {
      obj.finalRank = Math.round(message.final_rank);
    }
    if (message.joined_at !== undefined) {
      obj.joinedAt = message.joined_at.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LadderParticipant>, I>>(base?: I): LadderParticipant {
    return LadderParticipant.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LadderParticipant>, I>>(object: I): LadderParticipant {
    const message = createBaseLadderParticipant();
    message.ladder_id = object.ladder_id ?? "0";
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    message.final_rank = object.final_rank ?? 0;
    message.joined_at = object.joined_at ?? undefined;
    return message;
  },
};

function createBaseLadderLeaderboardEntry(): LadderLeaderboardEntry {
  return { participant: undefined };
}

export const LadderLeaderboardEntry: MessageFns<LadderLeaderboardEntry> = {
  encode(message: LadderLeaderboardEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.participant !== undefined) {
      LadderParticipant.encode(message.participant, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LadderLeaderboardEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLadderLeaderboardEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.participant = LadderParticipant.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LadderLeaderboardEntry {
    return { participant: isSet(object.participant) ? LadderParticipant.fromJSON(object.participant) : undefined };
  },

  toJSON(message: LadderLeaderboardEntry): unknown {
    const obj: any = {};
    if (message.participant !== undefined) {
      obj.participant = LadderParticipant.toJSON(message.participant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LadderLeaderboardEntry>, I>>(base?: I): LadderLeaderboardEntry {
    return LadderLeaderboardEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LadderLeaderboardEntry>, I>>(object: I): LadderLeaderboardEntry {
    const message = createBaseLadderLeaderboardEntry();
    message.participant = (object.participant !== undefined && object.participant !== null)
      ? LadderParticipant.fromPartial(object.participant)
      : undefined;
    return message;
  },
};

function createBaseListLaddersRequest(): ListLaddersRequest {
  return {};
}

export const ListLaddersRequest: MessageFns<ListLaddersRequest> = {
  encode(_: ListLaddersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListLaddersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListLaddersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListLaddersRequest {
    return {};
  },

  toJSON(_: ListLaddersRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListLaddersRequest>, I>>(base?: I): ListLaddersRequest {
    return ListLaddersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListLaddersRequest>, I>>(_: I): ListLaddersRequest {
    const message = createBaseListLaddersRequest();
    return message;
  },
};

function createBaseListLaddersResponse(): ListLaddersResponse {
  return { ladders: [] };
}

export const ListLaddersResponse: MessageFns<ListLaddersResponse> = {
  encode(message: ListLaddersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.ladders) {
      Ladder.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListLaddersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListLaddersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ladders.push(Ladder.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListLaddersResponse {
    return {
      ladders: globalThis.Array.isArray(object?.ladders) ? object.ladders.map((e: any) => Ladder.fromJSON(e)) : [],
    };
  },

  toJSON(message: ListLaddersResponse): unknown {
    const obj: any = {};
    if (message.ladders?.length) {
      obj.ladders = message.ladders.map((e) => Ladder.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListLaddersResponse>, I>>(base?: I): ListLaddersResponse {
    return ListLaddersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListLaddersResponse>, I>>(object: I): ListLaddersResponse {
    const message = createBaseListLaddersResponse();
    message.ladders = object.ladders?.map((e) => Ladder.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetActiveLadderRequest(): GetActiveLadderRequest {
  return {};
}

export const GetActiveLadderRequest: MessageFns<GetActiveLadderRequest> = {
  encode(_: GetActiveLadderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetActiveLadderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetActiveLadderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetActiveLadderRequest {
    return {};
  },

  toJSON(_: GetActiveLadderRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetActiveLadderRequest>, I>>(base?: I): GetActiveLadderRequest {
    return GetActiveLadderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetActiveLadderRequest>, I>>(_: I): GetActiveLadderRequest {
    const message = createBaseGetActiveLadderRequest();
    return message;
  },
};

function createBaseGetActiveLadderResponse(): GetActiveLadderResponse {
  return { ladder: undefined };
}

export const GetActiveLadderResponse: MessageFns<GetActiveLadderResponse> = {
  encode(message: GetActiveLadderResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ladder !== undefined) {
      Ladder.encode(message.ladder, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetActiveLadderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetActiveLadderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ladder = Ladder.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetActiveLadderResponse {
    return { ladder: isSet(object.ladder) ? Ladder.fromJSON(object.ladder) : undefined };
  },

  toJSON(message: GetActiveLadderResponse): unknown {
    const obj: any = {};
    if (message.ladder !== undefined) {
      obj.ladder = Ladder.toJSON(message.ladder);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetActiveLadderResponse>, I>>(base?: I): GetActiveLadderResponse {
    return GetActiveLadderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetActiveLadderResponse>, I>>(object: I): GetActiveLadderResponse {
    const message = createBaseGetActiveLadderResponse();
    message.ladder = (object.ladder !== undefined && object.ladder !== null)
      ? Ladder.fromPartial(object.ladder)
      : undefined;
    return message;
  },
};

function createBaseGetLadderLeaderboardRequest(): GetLadderLeaderboardRequest {
  return { ladder_id: "0", limit: 0 };
}

export const GetLadderLeaderboardRequest: MessageFns<GetLadderLeaderboardRequest> = {
  encode(message: GetLadderLeaderboardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ladder_id !== "0") {
      writer.uint32(8).int64(message.ladder_id);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLadderLeaderboardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLadderLeaderboardRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ladder_id = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetLadderLeaderboardRequest {
    return {
      ladder_id: isSet(object.ladderId)
        ? globalThis.String(object.ladderId)
        : isSet(object.ladder_id)
        ? globalThis.String(object.ladder_id)
        : "0",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: GetLadderLeaderboardRequest): unknown {
    const obj: any = {};
    if (message.ladder_id !== "0") {
      obj.ladderId = message.ladder_id;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetLadderLeaderboardRequest>, I>>(base?: I): GetLadderLeaderboardRequest {
    return GetLadderLeaderboardRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetLadderLeaderboardRequest>, I>>(object: I): GetLadderLeaderboardRequest {
    const message = createBaseGetLadderLeaderboardRequest();
    message.ladder_id = object.ladder_id ?? "0";
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseGetLadderLeaderboardResponse(): GetLadderLeaderboardResponse {
  return { entries: [] };
}

export const GetLadderLeaderboardResponse: MessageFns<GetLadderLeaderboardResponse> = {
  encode(message: GetLadderLeaderboardResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entries) {
      LadderLeaderboardEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLadderLeaderboardResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLadderLeaderboardResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entries.push(LadderLeaderboardEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetLadderLeaderboardResponse {
    return {
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => LadderLeaderboardEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetLadderLeaderboardResponse): unknown {
    const obj: any = {};
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => LadderLeaderboardEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetLadderLeaderboardResponse>, I>>(base?: I): GetLadderLeaderboardResponse {
    return GetLadderLeaderboardResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetLadderLeaderboardResponse>, I>>(object: I): GetLadderLeaderboardResponse {
    const message = createBaseGetLadderLeaderboardResponse();
    message.entries = object.entries?.map((e) => LadderLeaderboardEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetMyLadderStatsRequest(): GetMyLadderStatsRequest {
  return { ladder_id: "0" };
}

export const GetMyLadderStatsRequest: MessageFns<GetMyLadderStatsRequest> = {
  encode(message: GetMyLadderStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ladder_id !== "0") {
      writer.uint32(8).int64(message.ladder_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMyLadderStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMyLadderStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ladder_id = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMyLadderStatsRequest {
    return {
      ladder_id: isSet(object.ladderId)
        ? globalThis.String(object.ladderId)
        : isSet(object.ladder_id)
        ? globalThis.String(object.ladder_id)
        : "0",
    };
  },

  toJSON(message: GetMyLadderStatsRequest): unknown {
    const obj: any = {};
    if (message.ladder_id !== "0") {
      obj.ladderId = message.ladder_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMyLadderStatsRequest>, I>>(base?: I): GetMyLadderStatsRequest {
    return GetMyLadderStatsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMyLadderStatsRequest>, I>>(object: I): GetMyLadderStatsRequest {
    const message = createBaseGetMyLadderStatsRequest();
    message.ladder_id = object.ladder_id ?? "0";
    return message;
  },
};

function createBaseGetMyLadderStatsResponse(): GetMyLadderStatsResponse {
  return { participant: undefined };
}

export const GetMyLadderStatsResponse: MessageFns<GetMyLadderStatsResponse> = {
  encode(message: GetMyLadderStatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.participant !== undefined) {
      LadderParticipant.encode(message.participant, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMyLadderStatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMyLadderStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.participant = LadderParticipant.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMyLadderStatsResponse {
    return { participant: isSet(object.participant) ? LadderParticipant.fromJSON(object.participant) : undefined };
  },

  toJSON(message: GetMyLadderStatsResponse): unknown {
    const obj: any = {};
    if (message.participant !== undefined) {
      obj.participant = LadderParticipant.toJSON(message.participant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMyLadderStatsResponse>, I>>(base?: I): GetMyLadderStatsResponse {
    return GetMyLadderStatsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMyLadderStatsResponse>, I>>(object: I): GetMyLadderStatsResponse {
    const message = createBaseGetMyLadderStatsResponse();
    message.participant = (object.participant !== undefined && object.participant !== null)
      ? LadderParticipant.fromPartial(object.participant)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
