// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: exchange/v1/exchange.proto

package exchange

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Change        float64                `protobuf:"fixed64,3,opt,name=change,proto3" json:"change,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,4,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_exchange_v1_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_exchange_v1_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *Quote) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Quote) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Quote) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *Quote) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *Quote) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Quote) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteRequest) Reset() {
	*x = GetQuoteRequest{}
	mi := &file_exchange_v1_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteRequest) ProtoMessage() {}

func (x *GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_exchange_v1_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quote         *Quote                 `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteResponse) Reset() {
	*x = GetQuoteResponse{}
	mi := &file_exchange_v1_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteResponse) ProtoMessage() {}

func (x *GetQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return file_exchange_v1_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuoteResponse) GetQuote() *Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

type BuyStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyStockRequest) Reset() {
	*x = BuyStockRequest{}
	mi := &file_exchange_v1_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyStockRequest) ProtoMessage() {}

func (x *BuyStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyStockRequest.ProtoReflect.Descriptor instead.
func (*BuyStockRequest) Descriptor() ([]byte, []int) {
	return file_exchange_v1_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *BuyStockRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BuyStockRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BuyStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyStockResponse) Reset() {
	*x = BuyStockResponse{}
	mi := &file_exchange_v1_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyStockResponse) ProtoMessage() {}

func (x *BuyStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyStockResponse.ProtoReflect.Descriptor instead.
func (*BuyStockResponse) Descriptor() ([]byte, []int) {
	return file_exchange_v1_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *BuyStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuyStockResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *BuyStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SellStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellStockRequest) Reset() {
	*x = SellStockRequest{}
	mi := &file_exchange_v1_exchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellStockRequest) ProtoMessage() {}

func (x *SellStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_exchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellStockRequest.ProtoReflect.Descriptor instead.
func (*SellStockRequest) Descriptor() ([]byte, []int) {
	return file_exchange_v1_exchange_proto_rawDescGZIP(), []int{5}
}

func (x *SellStockRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SellStockRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type SellStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TotalProceeds float64                `protobuf:"fixed64,2,opt,name=total_proceeds,json=totalProceeds,proto3" json:"total_proceeds,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellStockResponse) Reset() {
	*x = SellStockResponse{}
	mi := &file_exchange_v1_exchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellStockResponse) ProtoMessage() {}

func (x *SellStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_exchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellStockResponse.ProtoReflect.Descriptor instead.
func (*SellStockResponse) Descriptor() ([]byte, []int) {
	return file_exchange_v1_exchange_proto_rawDescGZIP(), []int{6}
}

func (x *SellStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SellStockResponse) GetTotalProceeds() float64 {
	if x != nil {
		return x.TotalProceeds
	}
	return 0
}

func (x *SellStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_exchange_v1_exchange_proto protoreflect.FileDescriptor

const file_exchange_v1_exchange_proto_rawDesc = "" +
	"\n" +
	"\x1aexchange/v1/exchange.proto\x12\vexchange.v1\"\xaa\x01\n" +
	"\x05Quote\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06change\x18\x03 \x01(\x01R\x06change\x12%\n" +
	"\x0echange_percent\x18\x04 \x01(\x01R\rchangePercent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\")\n" +
	"\x0fGetQuoteRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"<\n" +
	"\x10GetQuoteResponse\x12(\n" +
	"\x05quote\x18\x01 \x01(\v2\x12.exchange.v1.QuoteR\x05quote\"E\n" +
	"\x0fBuyStockRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\"g\n" +
	"\x10BuyStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x01R\n" +
	"totalPrice\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"F\n" +
	"\x10SellStockRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\"n\n" +
	"\x11SellStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etotal_proceeds\x18\x02 \x01(\x01R\rtotalProceeds\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xef\x01\n" +
	"\x0fExchangeService\x12G\n" +
	"\bGetQuote\x12\x1c.exchange.v1.GetQuoteRequest\x1a\x1d.exchange.v1.GetQuoteResponse\x12G\n" +
	"\bBuyStock\x12\x1c.exchange.v1.BuyStockRequest\x1a\x1d.exchange.v1.BuyStockResponse\x12J\n" +
	"\tSellStock\x12\x1d.exchange.v1.SellStockRequest\x1a\x1e.exchange.v1.SellStockResponseBOZMgithub.com/tmythicator/ticker-rush/server/internal/proto/exchange/v1;exchangeb\x06proto3"

var (
	file_exchange_v1_exchange_proto_rawDescOnce sync.Once
	file_exchange_v1_exchange_proto_rawDescData []byte
)

func file_exchange_v1_exchange_proto_rawDescGZIP() []byte {
	file_exchange_v1_exchange_proto_rawDescOnce.Do(func() {
		file_exchange_v1_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exchange_v1_exchange_proto_rawDesc), len(file_exchange_v1_exchange_proto_rawDesc)))
	})
	return file_exchange_v1_exchange_proto_rawDescData
}

var file_exchange_v1_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_exchange_v1_exchange_proto_goTypes = []any{
	(*Quote)(nil),             // 0: exchange.v1.Quote
	(*GetQuoteRequest)(nil),   // 1: exchange.v1.GetQuoteRequest
	(*GetQuoteResponse)(nil),  // 2: exchange.v1.GetQuoteResponse
	(*BuyStockRequest)(nil),   // 3: exchange.v1.BuyStockRequest
	(*BuyStockResponse)(nil),  // 4: exchange.v1.BuyStockResponse
	(*SellStockRequest)(nil),  // 5: exchange.v1.SellStockRequest
	(*SellStockResponse)(nil), // 6: exchange.v1.SellStockResponse
}
var file_exchange_v1_exchange_proto_depIdxs = []int32{
	0, // 0: exchange.v1.GetQuoteResponse.quote:type_name -> exchange.v1.Quote
	1, // 1: exchange.v1.ExchangeService.GetQuote:input_type -> exchange.v1.GetQuoteRequest
	3, // 2: exchange.v1.ExchangeService.BuyStock:input_type -> exchange.v1.BuyStockRequest
	5, // 3: exchange.v1.ExchangeService.SellStock:input_type -> exchange.v1.SellStockRequest
	2, // 4: exchange.v1.ExchangeService.GetQuote:output_type -> exchange.v1.GetQuoteResponse
	4, // 5: exchange.v1.ExchangeService.BuyStock:output_type -> exchange.v1.BuyStockResponse
	6, // 6: exchange.v1.ExchangeService.SellStock:output_type -> exchange.v1.SellStockResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exchange_v1_exchange_proto_init() }
func file_exchange_v1_exchange_proto_init() {
	if File_exchange_v1_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exchange_v1_exchange_proto_rawDesc), len(file_exchange_v1_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exchange_v1_exchange_proto_goTypes,
		DependencyIndexes: file_exchange_v1_exchange_proto_depIdxs,
		MessageInfos:      file_exchange_v1_exchange_proto_msgTypes,
	}.Build()
	File_exchange_v1_exchange_proto = out.File
	file_exchange_v1_exchange_proto_goTypes = nil
	file_exchange_v1_exchange_proto_depIdxs = nil
}
