# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exchange/exchange.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'exchange/exchange.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65xchange/exchange.proto\x12\x08\x65xchange\"\x92\x01\n\x05Quote\x12\x16\n\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n\x06\x63hange\x18\x03 \x01(\x01R\x06\x63hange\x12%\n\x0e\x63hange_percent\x18\x04 \x01(\x01R\rchangePercent\x12\x1c\n\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\")\n\x0fGetQuoteRequest\x12\x16\n\x06symbol\x18\x01 \x01(\tR\x06symbol\"9\n\x10GetQuoteResponse\x12%\n\x05quote\x18\x01 \x01(\x0b\x32\x0f.exchange.QuoteR\x05quote\"E\n\x0f\x42uyStockRequest\x12\x16\n\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n\x08quantity\x18\x02 \x01(\x01R\x08quantity\"g\n\x10\x42uyStockResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x1f\n\x0btotal_price\x18\x02 \x01(\x01R\ntotalPrice\x12\x18\n\x07message\x18\x03 \x01(\tR\x07message\"F\n\x10SellStockRequest\x12\x16\n\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n\x08quantity\x18\x02 \x01(\x01R\x08quantity\"n\n\x11SellStockResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12%\n\x0etotal_proceeds\x18\x02 \x01(\x01R\rtotalProceeds\x12\x18\n\x07message\x18\x03 \x01(\tR\x07message2\xdd\x01\n\x0f\x45xchangeService\x12\x41\n\x08GetQuote\x12\x19.exchange.GetQuoteRequest\x1a\x1a.exchange.GetQuoteResponse\x12\x41\n\x08\x42uyStock\x12\x19.exchange.BuyStockRequest\x1a\x1a.exchange.BuyStockResponse\x12\x44\n\tSellStock\x12\x1a.exchange.SellStockRequest\x1a\x1b.exchange.SellStockResponseBCZAgithub.com/tmythicator/ticker-rush/server/internal/proto/exchangeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exchange.exchange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/tmythicator/ticker-rush/server/internal/proto/exchange'
  _globals['_QUOTE']._serialized_start=38
  _globals['_QUOTE']._serialized_end=184
  _globals['_GETQUOTEREQUEST']._serialized_start=186
  _globals['_GETQUOTEREQUEST']._serialized_end=227
  _globals['_GETQUOTERESPONSE']._serialized_start=229
  _globals['_GETQUOTERESPONSE']._serialized_end=286
  _globals['_BUYSTOCKREQUEST']._serialized_start=288
  _globals['_BUYSTOCKREQUEST']._serialized_end=357
  _globals['_BUYSTOCKRESPONSE']._serialized_start=359
  _globals['_BUYSTOCKRESPONSE']._serialized_end=462
  _globals['_SELLSTOCKREQUEST']._serialized_start=464
  _globals['_SELLSTOCKREQUEST']._serialized_end=534
  _globals['_SELLSTOCKRESPONSE']._serialized_start=536
  _globals['_SELLSTOCKRESPONSE']._serialized_end=646
  _globals['_EXCHANGESERVICE']._serialized_start=649
  _globals['_EXCHANGESERVICE']._serialized_end=870
# @@protoc_insertion_point(module_scope)
