# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from exchange import exchange_pb2 as exchange_dot_exchange__pb2


class ExchangeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQuote = channel.unary_unary(
                '/exchange.ExchangeService/GetQuote',
                request_serializer=exchange_dot_exchange__pb2.GetQuoteRequest.SerializeToString,
                response_deserializer=exchange_dot_exchange__pb2.GetQuoteResponse.FromString,
                _registered_method=True)
        self.BuyStock = channel.unary_unary(
                '/exchange.ExchangeService/BuyStock',
                request_serializer=exchange_dot_exchange__pb2.BuyStockRequest.SerializeToString,
                response_deserializer=exchange_dot_exchange__pb2.BuyStockResponse.FromString,
                _registered_method=True)
        self.SellStock = channel.unary_unary(
                '/exchange.ExchangeService/SellStock',
                request_serializer=exchange_dot_exchange__pb2.SellStockRequest.SerializeToString,
                response_deserializer=exchange_dot_exchange__pb2.SellStockResponse.FromString,
                _registered_method=True)


class ExchangeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuote,
                    request_deserializer=exchange_dot_exchange__pb2.GetQuoteRequest.FromString,
                    response_serializer=exchange_dot_exchange__pb2.GetQuoteResponse.SerializeToString,
            ),
            'BuyStock': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyStock,
                    request_deserializer=exchange_dot_exchange__pb2.BuyStockRequest.FromString,
                    response_serializer=exchange_dot_exchange__pb2.BuyStockResponse.SerializeToString,
            ),
            'SellStock': grpc.unary_unary_rpc_method_handler(
                    servicer.SellStock,
                    request_deserializer=exchange_dot_exchange__pb2.SellStockRequest.FromString,
                    response_serializer=exchange_dot_exchange__pb2.SellStockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exchange.ExchangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exchange.ExchangeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExchangeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.ExchangeService/GetQuote',
            exchange_dot_exchange__pb2.GetQuoteRequest.SerializeToString,
            exchange_dot_exchange__pb2.GetQuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuyStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.ExchangeService/BuyStock',
            exchange_dot_exchange__pb2.BuyStockRequest.SerializeToString,
            exchange_dot_exchange__pb2.BuyStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SellStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.ExchangeService/SellStock',
            exchange_dot_exchange__pb2.SellStockRequest.SerializeToString,
            exchange_dot_exchange__pb2.SellStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
