// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: ladder/v1/ladder.proto

package ladder

import (
	_ "github.com/tmythicator/ticker-rush/backend/internal/proto/user/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ladder represents a competition cycle.
type Ladder struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive       bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	InitialBalance float64                `protobuf:"fixed64,8,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	AllowedTickers []string               `protobuf:"bytes,9,rep,name=allowed_tickers,json=allowedTickers,proto3" json:"allowed_tickers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ladder) Reset() {
	*x = Ladder{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ladder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ladder) ProtoMessage() {}

func (x *Ladder) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ladder.ProtoReflect.Descriptor instead.
func (*Ladder) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{0}
}

func (x *Ladder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ladder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ladder) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Ladder) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Ladder) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Ladder) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Ladder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Ladder) GetInitialBalance() float64 {
	if x != nil {
		return x.InitialBalance
	}
	return 0
}

func (x *Ladder) GetAllowedTickers() []string {
	if x != nil {
		return x.AllowedTickers
	}
	return nil
}

type PortfolioItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockSymbol   string                 `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AveragePrice  float64                `protobuf:"fixed64,3,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioItem) Reset() {
	*x = PortfolioItem{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioItem) ProtoMessage() {}

func (x *PortfolioItem) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioItem.ProtoReflect.Descriptor instead.
func (*PortfolioItem) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{1}
}

func (x *PortfolioItem) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *PortfolioItem) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PortfolioItem) GetAveragePrice() float64 {
	if x != nil {
		return x.AveragePrice
	}
	return 0
}

// LadderParticipant represents a user's standing in a ladder.
type LadderParticipant struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	LadderId         int64                     `protobuf:"varint,1,opt,name=ladder_id,json=ladderId,proto3" json:"ladder_id,omitempty"`
	UserId           int64                     `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AvailableBalance float64                   `protobuf:"fixed64,3,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	FinalBalance     float64                   `protobuf:"fixed64,4,opt,name=final_balance,json=finalBalance,proto3" json:"final_balance,omitempty"`
	FinalRank        int32                     `protobuf:"varint,5,opt,name=final_rank,json=finalRank,proto3" json:"final_rank,omitempty"`
	CreatedAt        *timestamppb.Timestamp    `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Portfolio        map[string]*PortfolioItem `protobuf:"bytes,7,rep,name=portfolio,proto3" json:"portfolio,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LadderParticipant) Reset() {
	*x = LadderParticipant{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LadderParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LadderParticipant) ProtoMessage() {}

func (x *LadderParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LadderParticipant.ProtoReflect.Descriptor instead.
func (*LadderParticipant) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{2}
}

func (x *LadderParticipant) GetLadderId() int64 {
	if x != nil {
		return x.LadderId
	}
	return 0
}

func (x *LadderParticipant) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LadderParticipant) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *LadderParticipant) GetFinalBalance() float64 {
	if x != nil {
		return x.FinalBalance
	}
	return 0
}

func (x *LadderParticipant) GetFinalRank() int32 {
	if x != nil {
		return x.FinalRank
	}
	return 0
}

func (x *LadderParticipant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LadderParticipant) GetPortfolio() map[string]*PortfolioItem {
	if x != nil {
		return x.Portfolio
	}
	return nil
}

type LadderLeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participant   *LadderParticipant     `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LadderLeaderboardEntry) Reset() {
	*x = LadderLeaderboardEntry{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LadderLeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LadderLeaderboardEntry) ProtoMessage() {}

func (x *LadderLeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LadderLeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LadderLeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{3}
}

func (x *LadderLeaderboardEntry) GetParticipant() *LadderParticipant {
	if x != nil {
		return x.Participant
	}
	return nil
}

func (x *LadderLeaderboardEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListLaddersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLaddersRequest) Reset() {
	*x = ListLaddersRequest{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLaddersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLaddersRequest) ProtoMessage() {}

func (x *ListLaddersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLaddersRequest.ProtoReflect.Descriptor instead.
func (*ListLaddersRequest) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{4}
}

type ListLaddersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ladders       []*Ladder              `protobuf:"bytes,1,rep,name=ladders,proto3" json:"ladders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLaddersResponse) Reset() {
	*x = ListLaddersResponse{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLaddersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLaddersResponse) ProtoMessage() {}

func (x *ListLaddersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLaddersResponse.ProtoReflect.Descriptor instead.
func (*ListLaddersResponse) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{5}
}

func (x *ListLaddersResponse) GetLadders() []*Ladder {
	if x != nil {
		return x.Ladders
	}
	return nil
}

type GetActiveLadderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveLadderRequest) Reset() {
	*x = GetActiveLadderRequest{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveLadderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveLadderRequest) ProtoMessage() {}

func (x *GetActiveLadderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveLadderRequest.ProtoReflect.Descriptor instead.
func (*GetActiveLadderRequest) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{6}
}

type GetActiveLadderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ladder        *Ladder                `protobuf:"bytes,1,opt,name=ladder,proto3" json:"ladder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveLadderResponse) Reset() {
	*x = GetActiveLadderResponse{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveLadderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveLadderResponse) ProtoMessage() {}

func (x *GetActiveLadderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveLadderResponse.ProtoReflect.Descriptor instead.
func (*GetActiveLadderResponse) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{7}
}

func (x *GetActiveLadderResponse) GetLadder() *Ladder {
	if x != nil {
		return x.Ladder
	}
	return nil
}

type GetLadderLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LadderId      int64                  `protobuf:"varint,1,opt,name=ladder_id,json=ladderId,proto3" json:"ladder_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLadderLeaderboardRequest) Reset() {
	*x = GetLadderLeaderboardRequest{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLadderLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLadderLeaderboardRequest) ProtoMessage() {}

func (x *GetLadderLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLadderLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLadderLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{8}
}

func (x *GetLadderLeaderboardRequest) GetLadderId() int64 {
	if x != nil {
		return x.LadderId
	}
	return 0
}

func (x *GetLadderLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLadderLeaderboardResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Entries       []*LadderLeaderboardEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLadderLeaderboardResponse) Reset() {
	*x = GetLadderLeaderboardResponse{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLadderLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLadderLeaderboardResponse) ProtoMessage() {}

func (x *GetLadderLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLadderLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLadderLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{9}
}

func (x *GetLadderLeaderboardResponse) GetEntries() []*LadderLeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetMyLadderStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LadderId      int64                  `protobuf:"varint,1,opt,name=ladder_id,json=ladderId,proto3" json:"ladder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyLadderStatsRequest) Reset() {
	*x = GetMyLadderStatsRequest{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyLadderStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyLadderStatsRequest) ProtoMessage() {}

func (x *GetMyLadderStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyLadderStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMyLadderStatsRequest) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{10}
}

func (x *GetMyLadderStatsRequest) GetLadderId() int64 {
	if x != nil {
		return x.LadderId
	}
	return 0
}

type GetMyLadderStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participant   *LadderParticipant     `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyLadderStatsResponse) Reset() {
	*x = GetMyLadderStatsResponse{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyLadderStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyLadderStatsResponse) ProtoMessage() {}

func (x *GetMyLadderStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyLadderStatsResponse.ProtoReflect.Descriptor instead.
func (*GetMyLadderStatsResponse) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{11}
}

func (x *GetMyLadderStatsResponse) GetParticipant() *LadderParticipant {
	if x != nil {
		return x.Participant
	}
	return nil
}

var File_ladder_v1_ladder_proto protoreflect.FileDescriptor

const file_ladder_v1_ladder_proto_rawDesc = "" +
	"\n" +
	"\x16ladder/v1/ladder.proto\x12\tladder.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12user/v1/user.proto\"\xdc\x02\n" +
	"\x06Ladder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12'\n" +
	"\x0finitial_balance\x18\b \x01(\x01R\x0einitialBalance\x12'\n" +
	"\x0fallowed_tickers\x18\t \x03(\tR\x0eallowedTickers\"s\n" +
	"\rPortfolioItem\x12!\n" +
	"\fstock_symbol\x18\x01 \x01(\tR\vstockSymbol\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12#\n" +
	"\raverage_price\x18\x03 \x01(\x01R\faveragePrice\"\x98\x03\n" +
	"\x11LadderParticipant\x12\x1b\n" +
	"\tladder_id\x18\x01 \x01(\x03R\bladderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12+\n" +
	"\x11available_balance\x18\x03 \x01(\x01R\x10availableBalance\x12#\n" +
	"\rfinal_balance\x18\x04 \x01(\x01R\ffinalBalance\x12\x1d\n" +
	"\n" +
	"final_rank\x18\x05 \x01(\x05R\tfinalRank\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12I\n" +
	"\tportfolio\x18\a \x03(\v2+.ladder.v1.LadderParticipant.PortfolioEntryR\tportfolio\x1aV\n" +
	"\x0ePortfolioEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.ladder.v1.PortfolioItemR\x05value:\x028\x01\"t\n" +
	"\x16LadderLeaderboardEntry\x12>\n" +
	"\vparticipant\x18\x01 \x01(\v2\x1c.ladder.v1.LadderParticipantR\vparticipant\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x14\n" +
	"\x12ListLaddersRequest\"B\n" +
	"\x13ListLaddersResponse\x12+\n" +
	"\aladders\x18\x01 \x03(\v2\x11.ladder.v1.LadderR\aladders\"\x18\n" +
	"\x16GetActiveLadderRequest\"D\n" +
	"\x17GetActiveLadderResponse\x12)\n" +
	"\x06ladder\x18\x01 \x01(\v2\x11.ladder.v1.LadderR\x06ladder\"P\n" +
	"\x1bGetLadderLeaderboardRequest\x12\x1b\n" +
	"\tladder_id\x18\x01 \x01(\x03R\bladderId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"[\n" +
	"\x1cGetLadderLeaderboardResponse\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.ladder.v1.LadderLeaderboardEntryR\aentries\"6\n" +
	"\x17GetMyLadderStatsRequest\x12\x1b\n" +
	"\tladder_id\x18\x01 \x01(\x03R\bladderId\"Z\n" +
	"\x18GetMyLadderStatsResponse\x12>\n" +
	"\vparticipant\x18\x01 \x01(\v2\x1c.ladder.v1.LadderParticipantR\vparticipantBLZJgithub.com/tmythicator/ticker-rush/backend/internal/proto/ladder/v1;ladderb\x06proto3"

var (
	file_ladder_v1_ladder_proto_rawDescOnce sync.Once
	file_ladder_v1_ladder_proto_rawDescData []byte
)

func file_ladder_v1_ladder_proto_rawDescGZIP() []byte {
	file_ladder_v1_ladder_proto_rawDescOnce.Do(func() {
		file_ladder_v1_ladder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ladder_v1_ladder_proto_rawDesc), len(file_ladder_v1_ladder_proto_rawDesc)))
	})
	return file_ladder_v1_ladder_proto_rawDescData
}

var file_ladder_v1_ladder_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ladder_v1_ladder_proto_goTypes = []any{
	(*Ladder)(nil),                       // 0: ladder.v1.Ladder
	(*PortfolioItem)(nil),                // 1: ladder.v1.PortfolioItem
	(*LadderParticipant)(nil),            // 2: ladder.v1.LadderParticipant
	(*LadderLeaderboardEntry)(nil),       // 3: ladder.v1.LadderLeaderboardEntry
	(*ListLaddersRequest)(nil),           // 4: ladder.v1.ListLaddersRequest
	(*ListLaddersResponse)(nil),          // 5: ladder.v1.ListLaddersResponse
	(*GetActiveLadderRequest)(nil),       // 6: ladder.v1.GetActiveLadderRequest
	(*GetActiveLadderResponse)(nil),      // 7: ladder.v1.GetActiveLadderResponse
	(*GetLadderLeaderboardRequest)(nil),  // 8: ladder.v1.GetLadderLeaderboardRequest
	(*GetLadderLeaderboardResponse)(nil), // 9: ladder.v1.GetLadderLeaderboardResponse
	(*GetMyLadderStatsRequest)(nil),      // 10: ladder.v1.GetMyLadderStatsRequest
	(*GetMyLadderStatsResponse)(nil),     // 11: ladder.v1.GetMyLadderStatsResponse
	nil,                                  // 12: ladder.v1.LadderParticipant.PortfolioEntry
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
}
var file_ladder_v1_ladder_proto_depIdxs = []int32{
	13, // 0: ladder.v1.Ladder.start_time:type_name -> google.protobuf.Timestamp
	13, // 1: ladder.v1.Ladder.end_time:type_name -> google.protobuf.Timestamp
	13, // 2: ladder.v1.Ladder.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: ladder.v1.LadderParticipant.created_at:type_name -> google.protobuf.Timestamp
	12, // 4: ladder.v1.LadderParticipant.portfolio:type_name -> ladder.v1.LadderParticipant.PortfolioEntry
	2,  // 5: ladder.v1.LadderLeaderboardEntry.participant:type_name -> ladder.v1.LadderParticipant
	0,  // 6: ladder.v1.ListLaddersResponse.ladders:type_name -> ladder.v1.Ladder
	0,  // 7: ladder.v1.GetActiveLadderResponse.ladder:type_name -> ladder.v1.Ladder
	3,  // 8: ladder.v1.GetLadderLeaderboardResponse.entries:type_name -> ladder.v1.LadderLeaderboardEntry
	2,  // 9: ladder.v1.GetMyLadderStatsResponse.participant:type_name -> ladder.v1.LadderParticipant
	1,  // 10: ladder.v1.LadderParticipant.PortfolioEntry.value:type_name -> ladder.v1.PortfolioItem
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ladder_v1_ladder_proto_init() }
func file_ladder_v1_ladder_proto_init() {
	if File_ladder_v1_ladder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ladder_v1_ladder_proto_rawDesc), len(file_ladder_v1_ladder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ladder_v1_ladder_proto_goTypes,
		DependencyIndexes: file_ladder_v1_ladder_proto_depIdxs,
		MessageInfos:      file_ladder_v1_ladder_proto_msgTypes,
	}.Build()
	File_ladder_v1_ladder_proto = out.File
	file_ladder_v1_ladder_proto_goTypes = nil
	file_ladder_v1_ladder_proto_depIdxs = nil
}
