// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ladder/v1/ladder.proto

package ladder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LadderService_GetActiveLadder_FullMethodName = "/ladder.v1.LadderService/GetActiveLadder"
	LadderService_JoinLadder_FullMethodName      = "/ladder.v1.LadderService/JoinLadder"
)

// LadderServiceClient is the client API for LadderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LadderService manages active competition cycles and handles user enrollment.
type LadderServiceClient interface {
	// GetActiveLadder retrieves full metadata for the currently active ladder.
	GetActiveLadder(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetActiveLadderResponse, error)
	// JoinLadder enrolls the authenticated user into the active ladder competition.
	JoinLadder(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JoinLadderResponse, error)
}

type ladderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLadderServiceClient(cc grpc.ClientConnInterface) LadderServiceClient {
	return &ladderServiceClient{cc}
}

func (c *ladderServiceClient) GetActiveLadder(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetActiveLadderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveLadderResponse)
	err := c.cc.Invoke(ctx, LadderService_GetActiveLadder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ladderServiceClient) JoinLadder(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JoinLadderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinLadderResponse)
	err := c.cc.Invoke(ctx, LadderService_JoinLadder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LadderServiceServer is the server API for LadderService service.
// All implementations must embed UnimplementedLadderServiceServer
// for forward compatibility.
//
// LadderService manages active competition cycles and handles user enrollment.
type LadderServiceServer interface {
	// GetActiveLadder retrieves full metadata for the currently active ladder.
	GetActiveLadder(context.Context, *emptypb.Empty) (*GetActiveLadderResponse, error)
	// JoinLadder enrolls the authenticated user into the active ladder competition.
	JoinLadder(context.Context, *emptypb.Empty) (*JoinLadderResponse, error)
	mustEmbedUnimplementedLadderServiceServer()
}

// UnimplementedLadderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLadderServiceServer struct{}

func (UnimplementedLadderServiceServer) GetActiveLadder(context.Context, *emptypb.Empty) (*GetActiveLadderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveLadder not implemented")
}
func (UnimplementedLadderServiceServer) JoinLadder(context.Context, *emptypb.Empty) (*JoinLadderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinLadder not implemented")
}
func (UnimplementedLadderServiceServer) mustEmbedUnimplementedLadderServiceServer() {}
func (UnimplementedLadderServiceServer) testEmbeddedByValue()                       {}

// UnsafeLadderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LadderServiceServer will
// result in compilation errors.
type UnsafeLadderServiceServer interface {
	mustEmbedUnimplementedLadderServiceServer()
}

func RegisterLadderServiceServer(s grpc.ServiceRegistrar, srv LadderServiceServer) {
	// If the following call panics, it indicates UnimplementedLadderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LadderService_ServiceDesc, srv)
}

func _LadderService_GetActiveLadder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LadderServiceServer).GetActiveLadder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LadderService_GetActiveLadder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LadderServiceServer).GetActiveLadder(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LadderService_JoinLadder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LadderServiceServer).JoinLadder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LadderService_JoinLadder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LadderServiceServer).JoinLadder(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// LadderService_ServiceDesc is the grpc.ServiceDesc for LadderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LadderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ladder.v1.LadderService",
	HandlerType: (*LadderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActiveLadder",
			Handler:    _LadderService_GetActiveLadder_Handler,
		},
		{
			MethodName: "JoinLadder",
			Handler:    _LadderService_JoinLadder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ladder/v1/ladder.proto",
}
