// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ladder/v1/ladder.proto

package ladder

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/tmythicator/ticker-rush/backend/internal/proto/user/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Competition cycle or season.
type Ladder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique database identifier.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the competition.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Type of competition cycle (weekly or monthly).
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Start time of the competition.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End time of the competition.
	EndTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Whether the ladder is currently active.
	IsActive bool `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Creation timestamp of the ladder.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Starting cash balance allocated to participants.
	InitialBalance float64 `protobuf:"fixed64,8,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	// List of stock tickers allowed in this competition.
	AllowedTickers []*TickerInfo `protobuf:"bytes,9,rep,name=allowed_tickers,json=allowedTickers,proto3" json:"allowed_tickers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ladder) Reset() {
	*x = Ladder{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ladder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ladder) ProtoMessage() {}

func (x *Ladder) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ladder.ProtoReflect.Descriptor instead.
func (*Ladder) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{0}
}

func (x *Ladder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ladder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ladder) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Ladder) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Ladder) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Ladder) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Ladder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Ladder) GetInitialBalance() float64 {
	if x != nil {
		return x.InitialBalance
	}
	return 0
}

func (x *Ladder) GetAllowedTickers() []*TickerInfo {
	if x != nil {
		return x.AllowedTickers
	}
	return nil
}

// Configuration of an allowed stock in the ladder.
type TickerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stock ticker symbol.
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Source provider for market data.
	Source        string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickerInfo) Reset() {
	*x = TickerInfo{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerInfo) ProtoMessage() {}

func (x *TickerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerInfo.ProtoReflect.Descriptor instead.
func (*TickerInfo) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{1}
}

func (x *TickerInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TickerInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// User standing and status in a ladder.
type LadderParticipant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the ladder.
	LadderId int64 `protobuf:"varint,1,opt,name=ladder_id,json=ladderId,proto3" json:"ladder_id,omitempty"`
	// User profile of the participant.
	User *v1.User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// Final rank in the ladder (set after completion).
	FinalRank int32 `protobuf:"varint,3,opt,name=final_rank,json=finalRank,proto3" json:"final_rank,omitempty"`
	// Timestamp when the user joined.
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LadderParticipant) Reset() {
	*x = LadderParticipant{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LadderParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LadderParticipant) ProtoMessage() {}

func (x *LadderParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LadderParticipant.ProtoReflect.Descriptor instead.
func (*LadderParticipant) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{2}
}

func (x *LadderParticipant) GetLadderId() int64 {
	if x != nil {
		return x.LadderId
	}
	return 0
}

func (x *LadderParticipant) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LadderParticipant) GetFinalRank() int32 {
	if x != nil {
		return x.FinalRank
	}
	return 0
}

func (x *LadderParticipant) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

// Response containing active ladder metadata.
type GetActiveLadderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Active competition ladder.
	Ladder        *Ladder `protobuf:"bytes,1,opt,name=ladder,proto3" json:"ladder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveLadderResponse) Reset() {
	*x = GetActiveLadderResponse{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveLadderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveLadderResponse) ProtoMessage() {}

func (x *GetActiveLadderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveLadderResponse.ProtoReflect.Descriptor instead.
func (*GetActiveLadderResponse) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{3}
}

func (x *GetActiveLadderResponse) GetLadder() *Ladder {
	if x != nil {
		return x.Ladder
	}
	return nil
}

// Response for joining a ladder.
type JoinLadderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the transaction succeeded.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Detailed status or error message.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLadderResponse) Reset() {
	*x = JoinLadderResponse{}
	mi := &file_ladder_v1_ladder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLadderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLadderResponse) ProtoMessage() {}

func (x *JoinLadderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ladder_v1_ladder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLadderResponse.ProtoReflect.Descriptor instead.
func (*JoinLadderResponse) Descriptor() ([]byte, []int) {
	return file_ladder_v1_ladder_proto_rawDescGZIP(), []int{4}
}

func (x *JoinLadderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinLadderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ladder_v1_ladder_proto protoreflect.FileDescriptor

const file_ladder_v1_ladder_proto_rawDesc = "" +
	"\n" +
	"\x16ladder/v1/ladder.proto\x12\tladder.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12user/v1/user.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xf3\x02\n" +
	"\x06Ladder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12'\n" +
	"\x0finitial_balance\x18\b \x01(\x01R\x0einitialBalance\x12>\n" +
	"\x0fallowed_tickers\x18\t \x03(\v2\x15.ladder.v1.TickerInfoR\x0eallowedTickers\"<\n" +
	"\n" +
	"TickerInfo\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"\xab\x01\n" +
	"\x11LadderParticipant\x12\x1b\n" +
	"\tladder_id\x18\x01 \x01(\x03R\bladderId\x12!\n" +
	"\x04user\x18\x02 \x01(\v2\r.user.v1.UserR\x04user\x12\x1d\n" +
	"\n" +
	"final_rank\x18\x03 \x01(\x05R\tfinalRank\x127\n" +
	"\tjoined_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"D\n" +
	"\x17GetActiveLadderResponse\x12)\n" +
	"\x06ladder\x18\x01 \x01(\v2\x11.ladder.v1.LadderR\x06ladder\"H\n" +
	"\x12JoinLadderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xee\x01\n" +
	"\rLadderService\x12i\n" +
	"\x0fGetActiveLadder\x12\x16.google.protobuf.Empty\x1a\".ladder.v1.GetActiveLadderResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/ladder/active\x12r\n" +
	"\n" +
	"JoinLadder\x12\x16.google.protobuf.Empty\x1a\x1d.ladder.v1.JoinLadderResponse\"-\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"CookieAuth\x12\x00\x82\xd3\xe4\x93\x02\x12\"\x10/api/ladder/joinB\xfd\x01\x92A\xad\x01\x12V\n" +
	"\x12Ladder Service API\x129API for viewing and participating in competition ladders.2\x051.0.0ZS\n" +
	"Q\n" +
	"\n" +
	"CookieAuth\x12C\b\x02\x121Authentication cookie 'auth_token' containing JWT\x1a\n" +
	"auth_token \x02ZJgithub.com/tmythicator/ticker-rush/backend/internal/proto/ladder/v1;ladderb\x06proto3"

var (
	file_ladder_v1_ladder_proto_rawDescOnce sync.Once
	file_ladder_v1_ladder_proto_rawDescData []byte
)

func file_ladder_v1_ladder_proto_rawDescGZIP() []byte {
	file_ladder_v1_ladder_proto_rawDescOnce.Do(func() {
		file_ladder_v1_ladder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ladder_v1_ladder_proto_rawDesc), len(file_ladder_v1_ladder_proto_rawDesc)))
	})
	return file_ladder_v1_ladder_proto_rawDescData
}

var file_ladder_v1_ladder_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ladder_v1_ladder_proto_goTypes = []any{
	(*Ladder)(nil),                  // 0: ladder.v1.Ladder
	(*TickerInfo)(nil),              // 1: ladder.v1.TickerInfo
	(*LadderParticipant)(nil),       // 2: ladder.v1.LadderParticipant
	(*GetActiveLadderResponse)(nil), // 3: ladder.v1.GetActiveLadderResponse
	(*JoinLadderResponse)(nil),      // 4: ladder.v1.JoinLadderResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
	(*v1.User)(nil),                 // 6: user.v1.User
	(*emptypb.Empty)(nil),           // 7: google.protobuf.Empty
}
var file_ladder_v1_ladder_proto_depIdxs = []int32{
	5, // 0: ladder.v1.Ladder.start_time:type_name -> google.protobuf.Timestamp
	5, // 1: ladder.v1.Ladder.end_time:type_name -> google.protobuf.Timestamp
	5, // 2: ladder.v1.Ladder.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: ladder.v1.Ladder.allowed_tickers:type_name -> ladder.v1.TickerInfo
	6, // 4: ladder.v1.LadderParticipant.user:type_name -> user.v1.User
	5, // 5: ladder.v1.LadderParticipant.joined_at:type_name -> google.protobuf.Timestamp
	0, // 6: ladder.v1.GetActiveLadderResponse.ladder:type_name -> ladder.v1.Ladder
	7, // 7: ladder.v1.LadderService.GetActiveLadder:input_type -> google.protobuf.Empty
	7, // 8: ladder.v1.LadderService.JoinLadder:input_type -> google.protobuf.Empty
	3, // 9: ladder.v1.LadderService.GetActiveLadder:output_type -> ladder.v1.GetActiveLadderResponse
	4, // 10: ladder.v1.LadderService.JoinLadder:output_type -> ladder.v1.JoinLadderResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_ladder_v1_ladder_proto_init() }
func file_ladder_v1_ladder_proto_init() {
	if File_ladder_v1_ladder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ladder_v1_ladder_proto_rawDesc), len(file_ladder_v1_ladder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ladder_v1_ladder_proto_goTypes,
		DependencyIndexes: file_ladder_v1_ladder_proto_depIdxs,
		MessageInfos:      file_ladder_v1_ladder_proto_msgTypes,
	}.Build()
	File_ladder_v1_ladder_proto = out.File
	file_ladder_v1_ladder_proto_goTypes = nil
	file_ladder_v1_ladder_proto_depIdxs = nil
}
