// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: user/v1/user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "user.v1";

export interface PortfolioItem {
  stock_symbol: string;
  quantity: number;
  average_price: number;
}

export interface User {
  id: string;
  username: string;
  password_hash: string;
  balance: number;
  created_at: Date | undefined;
  first_name: string;
  last_name: string;
  portfolio: { [key: string]: PortfolioItem };
  website: string;
}

export interface User_PortfolioEntry {
  key: string;
  value: PortfolioItem | undefined;
}

export interface CreateUserRequest {
  username: string;
  password: string;
  first_name: string;
  last_name: string;
  website: string;
}

export interface LoginRequest {
  username: string;
  password: string;
}

function createBasePortfolioItem(): PortfolioItem {
  return { stock_symbol: "", quantity: 0, average_price: 0 };
}

export const PortfolioItem: MessageFns<PortfolioItem> = {
  encode(message: PortfolioItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stock_symbol !== "") {
      writer.uint32(10).string(message.stock_symbol);
    }
    if (message.quantity !== 0) {
      writer.uint32(17).double(message.quantity);
    }
    if (message.average_price !== 0) {
      writer.uint32(25).double(message.average_price);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PortfolioItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePortfolioItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stock_symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.quantity = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.average_price = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PortfolioItem {
    return {
      stock_symbol: isSet(object.stockSymbol)
        ? globalThis.String(object.stockSymbol)
        : isSet(object.stock_symbol)
        ? globalThis.String(object.stock_symbol)
        : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      average_price: isSet(object.averagePrice)
        ? globalThis.Number(object.averagePrice)
        : isSet(object.average_price)
        ? globalThis.Number(object.average_price)
        : 0,
    };
  },

  toJSON(message: PortfolioItem): unknown {
    const obj: any = {};
    if (message.stock_symbol !== "") {
      obj.stockSymbol = message.stock_symbol;
    }
    if (message.quantity !== 0) {
      obj.quantity = message.quantity;
    }
    if (message.average_price !== 0) {
      obj.averagePrice = message.average_price;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PortfolioItem>, I>>(base?: I): PortfolioItem {
    return PortfolioItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PortfolioItem>, I>>(object: I): PortfolioItem {
    const message = createBasePortfolioItem();
    message.stock_symbol = object.stock_symbol ?? "";
    message.quantity = object.quantity ?? 0;
    message.average_price = object.average_price ?? 0;
    return message;
  },
};

function createBaseUser(): User {
  return {
    id: "0",
    username: "",
    password_hash: "",
    balance: 0,
    created_at: undefined,
    first_name: "",
    last_name: "",
    portfolio: {},
    website: "",
  };
}

export const User: MessageFns<User> = {
  encode(message: User, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "0") {
      writer.uint32(8).int64(message.id);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    if (message.password_hash !== "") {
      writer.uint32(26).string(message.password_hash);
    }
    if (message.balance !== 0) {
      writer.uint32(33).double(message.balance);
    }
    if (message.created_at !== undefined) {
      Timestamp.encode(toTimestamp(message.created_at), writer.uint32(42).fork()).join();
    }
    if (message.first_name !== "") {
      writer.uint32(50).string(message.first_name);
    }
    if (message.last_name !== "") {
      writer.uint32(58).string(message.last_name);
    }
    globalThis.Object.entries(message.portfolio).forEach(([key, value]: [string, PortfolioItem]) => {
      User_PortfolioEntry.encode({ key: key as any, value }, writer.uint32(66).fork()).join();
    });
    if (message.website !== "") {
      writer.uint32(74).string(message.website);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): User {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.password_hash = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.balance = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.created_at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.first_name = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.last_name = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          const entry8 = User_PortfolioEntry.decode(reader, reader.uint32());
          if (entry8.value !== undefined) {
            message.portfolio[entry8.key] = entry8.value;
          }
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.website = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): User {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "0",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password_hash: isSet(object.passwordHash)
        ? globalThis.String(object.passwordHash)
        : isSet(object.password_hash)
        ? globalThis.String(object.password_hash)
        : "",
      balance: isSet(object.balance) ? globalThis.Number(object.balance) : 0,
      created_at: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
        ? fromJsonTimestamp(object.created_at)
        : undefined,
      first_name: isSet(object.firstName)
        ? globalThis.String(object.firstName)
        : isSet(object.first_name)
        ? globalThis.String(object.first_name)
        : "",
      last_name: isSet(object.lastName)
        ? globalThis.String(object.lastName)
        : isSet(object.last_name)
        ? globalThis.String(object.last_name)
        : "",
      portfolio: isObject(object.portfolio)
        ? (globalThis.Object.entries(object.portfolio) as [string, any][]).reduce(
          (acc: { [key: string]: PortfolioItem }, [key, value]: [string, any]) => {
            acc[key] = PortfolioItem.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      website: isSet(object.website) ? globalThis.String(object.website) : "",
    };
  },

  toJSON(message: User): unknown {
    const obj: any = {};
    if (message.id !== "0") {
      obj.id = message.id;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password_hash !== "") {
      obj.passwordHash = message.password_hash;
    }
    if (message.balance !== 0) {
      obj.balance = message.balance;
    }
    if (message.created_at !== undefined) {
      obj.createdAt = message.created_at.toISOString();
    }
    if (message.first_name !== "") {
      obj.firstName = message.first_name;
    }
    if (message.last_name !== "") {
      obj.lastName = message.last_name;
    }
    if (message.portfolio) {
      const entries = globalThis.Object.entries(message.portfolio) as [string, PortfolioItem][];
      if (entries.length > 0) {
        obj.portfolio = {};
        entries.forEach(([k, v]) => {
          obj.portfolio[k] = PortfolioItem.toJSON(v);
        });
      }
    }
    if (message.website !== "") {
      obj.website = message.website;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<User>, I>>(base?: I): User {
    return User.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<User>, I>>(object: I): User {
    const message = createBaseUser();
    message.id = object.id ?? "0";
    message.username = object.username ?? "";
    message.password_hash = object.password_hash ?? "";
    message.balance = object.balance ?? 0;
    message.created_at = object.created_at ?? undefined;
    message.first_name = object.first_name ?? "";
    message.last_name = object.last_name ?? "";
    message.portfolio = (globalThis.Object.entries(object.portfolio ?? {}) as [string, PortfolioItem][]).reduce(
      (acc: { [key: string]: PortfolioItem }, [key, value]: [string, PortfolioItem]) => {
        if (value !== undefined) {
          acc[key] = PortfolioItem.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.website = object.website ?? "";
    return message;
  },
};

function createBaseUser_PortfolioEntry(): User_PortfolioEntry {
  return { key: "", value: undefined };
}

export const User_PortfolioEntry: MessageFns<User_PortfolioEntry> = {
  encode(message: User_PortfolioEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      PortfolioItem.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): User_PortfolioEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUser_PortfolioEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = PortfolioItem.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): User_PortfolioEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? PortfolioItem.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: User_PortfolioEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = PortfolioItem.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<User_PortfolioEntry>, I>>(base?: I): User_PortfolioEntry {
    return User_PortfolioEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<User_PortfolioEntry>, I>>(object: I): User_PortfolioEntry {
    const message = createBaseUser_PortfolioEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? PortfolioItem.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseCreateUserRequest(): CreateUserRequest {
  return { username: "", password: "", first_name: "", last_name: "", website: "" };
}

export const CreateUserRequest: MessageFns<CreateUserRequest> = {
  encode(message: CreateUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.first_name !== "") {
      writer.uint32(26).string(message.first_name);
    }
    if (message.last_name !== "") {
      writer.uint32(34).string(message.last_name);
    }
    if (message.website !== "") {
      writer.uint32(42).string(message.website);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.first_name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.last_name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.website = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateUserRequest {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      first_name: isSet(object.firstName)
        ? globalThis.String(object.firstName)
        : isSet(object.first_name)
        ? globalThis.String(object.first_name)
        : "",
      last_name: isSet(object.lastName)
        ? globalThis.String(object.lastName)
        : isSet(object.last_name)
        ? globalThis.String(object.last_name)
        : "",
      website: isSet(object.website) ? globalThis.String(object.website) : "",
    };
  },

  toJSON(message: CreateUserRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.first_name !== "") {
      obj.firstName = message.first_name;
    }
    if (message.last_name !== "") {
      obj.lastName = message.last_name;
    }
    if (message.website !== "") {
      obj.website = message.website;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateUserRequest>, I>>(base?: I): CreateUserRequest {
    return CreateUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateUserRequest>, I>>(object: I): CreateUserRequest {
    const message = createBaseCreateUserRequest();
    message.username = object.username ?? "";
    message.password = object.password ?? "";
    message.first_name = object.first_name ?? "";
    message.last_name = object.last_name ?? "";
    message.website = object.website ?? "";
    return message;
  },
};

function createBaseLoginRequest(): LoginRequest {
  return { username: "", password: "" };
}

export const LoginRequest: MessageFns<LoginRequest> = {
  encode(message: LoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginRequest {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: LoginRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginRequest>, I>>(base?: I): LoginRequest {
    return LoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginRequest>, I>>(object: I): LoginRequest {
    const message = createBaseLoginRequest();
    message.username = object.username ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
