// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: exchange/v1/exchange.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { LadderParticipant } from "../../ladder/v1/ladder";

export const protobufPackage = "exchange.v1";

/** Trade action type (Buy or Sell). */
export const TradeAction = { UNSPECIFIED: 0, BUY: 1, SELL: 2, UNRECOGNIZED: -1 } as const;

export type TradeAction = typeof TradeAction[keyof typeof TradeAction];

export namespace TradeAction {
  export type UNSPECIFIED = typeof TradeAction.UNSPECIFIED;
  export type BUY = typeof TradeAction.BUY;
  export type SELL = typeof TradeAction.SELL;
  export type UNRECOGNIZED = typeof TradeAction.UNRECOGNIZED;
}

export function tradeActionFromJSON(object: any): TradeAction {
  switch (object) {
    case 0:
    case "UNSPECIFIED":
      return TradeAction.UNSPECIFIED;
    case 1:
    case "BUY":
      return TradeAction.BUY;
    case 2:
    case "SELL":
      return TradeAction.SELL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TradeAction.UNRECOGNIZED;
  }
}

export function tradeActionToJSON(object: TradeAction): string {
  switch (object) {
    case TradeAction.UNSPECIFIED:
      return "UNSPECIFIED";
    case TradeAction.BUY:
      return "BUY";
    case TradeAction.SELL:
      return "SELL";
    case TradeAction.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Real-time stock price data. */
export interface Quote {
  /** Stock ticker symbol. */
  symbol: string;
  /** Current price in USD. */
  price: number;
  /** Absolute price change compared to the previous close. */
  change: number;
  /** Percentage price change compared to the previous close. */
  change_percent: number;
  /** Unix timestamp of the price update in seconds. */
  timestamp: string;
  /** Price data provider source. */
  source: string;
  /** Indicates if the market is closed for this stock. */
  is_closed: boolean;
}

/** Request to fetch a stock quote. */
export interface GetQuoteRequest {
  /** Stock ticker symbol. */
  symbol: string;
}

/** Response containing the stock quote. */
export interface GetQuoteResponse {
  /** Current stock quote. */
  quote: Quote | undefined;
}

/** Request to retrieve price history. */
export interface GetHistoryRequest {
  /** Stock ticker symbol. */
  symbol: string;
  /** Maximum number of historical records to return. */
  limit: number;
}

/** Response containing historical quote records. */
export interface GetHistoryResponse {
  /** Historical stock quote entries. */
  history: Quote[];
}

/** Request to establish a real-time quote stream. */
export interface StreamQuotesRequest {
  /** Optional ticker symbol to filter updates. If empty, streams all tickers. */
  symbol: string;
}

/** Response payload for real-time quote stream. */
export interface StreamQuotesResponse {
  /** Live stock quote update. */
  quote: Quote | undefined;
}

/** Request payload to place a trade. */
export interface CreateTradeRequest {
  /** Stock ticker symbol to trade. */
  symbol: string;
  /** Quantity of shares to trade. */
  quantity: number;
  /** Action to perform (Buy or Sell). */
  action: TradeAction;
}

/** Response payload for a trade transaction. */
export interface CreateTradeResponse {
  /** Whether the transaction succeeded. */
  success: boolean;
  /** Status or error message. */
  message: string;
  /** Updated standing and portfolio of the participant. */
  participant: LadderParticipant | undefined;
}

function createBaseQuote(): Quote {
  return { symbol: "", price: 0, change: 0, change_percent: 0, timestamp: "0", source: "", is_closed: false };
}

export const Quote: MessageFns<Quote> = {
  encode(message: Quote, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.price !== 0) {
      writer.uint32(17).double(message.price);
    }
    if (message.change !== 0) {
      writer.uint32(25).double(message.change);
    }
    if (message.change_percent !== 0) {
      writer.uint32(33).double(message.change_percent);
    }
    if (message.timestamp !== "0") {
      writer.uint32(40).int64(message.timestamp);
    }
    if (message.source !== "") {
      writer.uint32(50).string(message.source);
    }
    if (message.is_closed !== false) {
      writer.uint32(56).bool(message.is_closed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Quote {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuote();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.price = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.change = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.change_percent = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timestamp = reader.int64().toString();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.is_closed = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Quote {
    return {
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
      change: isSet(object.change) ? globalThis.Number(object.change) : 0,
      change_percent: isSet(object.changePercent)
        ? globalThis.Number(object.changePercent)
        : isSet(object.change_percent)
        ? globalThis.Number(object.change_percent)
        : 0,
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "0",
      source: isSet(object.source) ? globalThis.String(object.source) : "",
      is_closed: isSet(object.isClosed)
        ? globalThis.Boolean(object.isClosed)
        : isSet(object.is_closed)
        ? globalThis.Boolean(object.is_closed)
        : false,
    };
  },

  toJSON(message: Quote): unknown {
    const obj: any = {};
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    if (message.change !== 0) {
      obj.change = message.change;
    }
    if (message.change_percent !== 0) {
      obj.changePercent = message.change_percent;
    }
    if (message.timestamp !== "0") {
      obj.timestamp = message.timestamp;
    }
    if (message.source !== "") {
      obj.source = message.source;
    }
    if (message.is_closed !== false) {
      obj.isClosed = message.is_closed;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Quote>, I>>(base?: I): Quote {
    return Quote.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Quote>, I>>(object: I): Quote {
    const message = createBaseQuote();
    message.symbol = object.symbol ?? "";
    message.price = object.price ?? 0;
    message.change = object.change ?? 0;
    message.change_percent = object.change_percent ?? 0;
    message.timestamp = object.timestamp ?? "0";
    message.source = object.source ?? "";
    message.is_closed = object.is_closed ?? false;
    return message;
  },
};

function createBaseGetQuoteRequest(): GetQuoteRequest {
  return { symbol: "" };
}

export const GetQuoteRequest: MessageFns<GetQuoteRequest> = {
  encode(message: GetQuoteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetQuoteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetQuoteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetQuoteRequest {
    return { symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "" };
  },

  toJSON(message: GetQuoteRequest): unknown {
    const obj: any = {};
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetQuoteRequest>, I>>(base?: I): GetQuoteRequest {
    return GetQuoteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetQuoteRequest>, I>>(object: I): GetQuoteRequest {
    const message = createBaseGetQuoteRequest();
    message.symbol = object.symbol ?? "";
    return message;
  },
};

function createBaseGetQuoteResponse(): GetQuoteResponse {
  return { quote: undefined };
}

export const GetQuoteResponse: MessageFns<GetQuoteResponse> = {
  encode(message: GetQuoteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.quote !== undefined) {
      Quote.encode(message.quote, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetQuoteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetQuoteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.quote = Quote.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetQuoteResponse {
    return { quote: isSet(object.quote) ? Quote.fromJSON(object.quote) : undefined };
  },

  toJSON(message: GetQuoteResponse): unknown {
    const obj: any = {};
    if (message.quote !== undefined) {
      obj.quote = Quote.toJSON(message.quote);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetQuoteResponse>, I>>(base?: I): GetQuoteResponse {
    return GetQuoteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetQuoteResponse>, I>>(object: I): GetQuoteResponse {
    const message = createBaseGetQuoteResponse();
    message.quote = (object.quote !== undefined && object.quote !== null) ? Quote.fromPartial(object.quote) : undefined;
    return message;
  },
};

function createBaseGetHistoryRequest(): GetHistoryRequest {
  return { symbol: "", limit: 0 };
}

export const GetHistoryRequest: MessageFns<GetHistoryRequest> = {
  encode(message: GetHistoryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetHistoryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetHistoryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetHistoryRequest {
    return {
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: GetHistoryRequest): unknown {
    const obj: any = {};
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetHistoryRequest>, I>>(base?: I): GetHistoryRequest {
    return GetHistoryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetHistoryRequest>, I>>(object: I): GetHistoryRequest {
    const message = createBaseGetHistoryRequest();
    message.symbol = object.symbol ?? "";
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseGetHistoryResponse(): GetHistoryResponse {
  return { history: [] };
}

export const GetHistoryResponse: MessageFns<GetHistoryResponse> = {
  encode(message: GetHistoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.history) {
      Quote.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetHistoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetHistoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.history.push(Quote.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetHistoryResponse {
    return {
      history: globalThis.Array.isArray(object?.history) ? object.history.map((e: any) => Quote.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetHistoryResponse): unknown {
    const obj: any = {};
    if (message.history?.length) {
      obj.history = message.history.map((e) => Quote.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetHistoryResponse>, I>>(base?: I): GetHistoryResponse {
    return GetHistoryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetHistoryResponse>, I>>(object: I): GetHistoryResponse {
    const message = createBaseGetHistoryResponse();
    message.history = object.history?.map((e) => Quote.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStreamQuotesRequest(): StreamQuotesRequest {
  return { symbol: "" };
}

export const StreamQuotesRequest: MessageFns<StreamQuotesRequest> = {
  encode(message: StreamQuotesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamQuotesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamQuotesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamQuotesRequest {
    return { symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "" };
  },

  toJSON(message: StreamQuotesRequest): unknown {
    const obj: any = {};
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamQuotesRequest>, I>>(base?: I): StreamQuotesRequest {
    return StreamQuotesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamQuotesRequest>, I>>(object: I): StreamQuotesRequest {
    const message = createBaseStreamQuotesRequest();
    message.symbol = object.symbol ?? "";
    return message;
  },
};

function createBaseStreamQuotesResponse(): StreamQuotesResponse {
  return { quote: undefined };
}

export const StreamQuotesResponse: MessageFns<StreamQuotesResponse> = {
  encode(message: StreamQuotesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.quote !== undefined) {
      Quote.encode(message.quote, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamQuotesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamQuotesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.quote = Quote.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamQuotesResponse {
    return { quote: isSet(object.quote) ? Quote.fromJSON(object.quote) : undefined };
  },

  toJSON(message: StreamQuotesResponse): unknown {
    const obj: any = {};
    if (message.quote !== undefined) {
      obj.quote = Quote.toJSON(message.quote);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamQuotesResponse>, I>>(base?: I): StreamQuotesResponse {
    return StreamQuotesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamQuotesResponse>, I>>(object: I): StreamQuotesResponse {
    const message = createBaseStreamQuotesResponse();
    message.quote = (object.quote !== undefined && object.quote !== null) ? Quote.fromPartial(object.quote) : undefined;
    return message;
  },
};

function createBaseCreateTradeRequest(): CreateTradeRequest {
  return { symbol: "", quantity: 0, action: 0 };
}

export const CreateTradeRequest: MessageFns<CreateTradeRequest> = {
  encode(message: CreateTradeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.quantity !== 0) {
      writer.uint32(17).double(message.quantity);
    }
    if (message.action !== 0) {
      writer.uint32(24).int32(message.action);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTradeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTradeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.quantity = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.action = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTradeRequest {
    return {
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      action: isSet(object.action) ? tradeActionFromJSON(object.action) : 0,
    };
  },

  toJSON(message: CreateTradeRequest): unknown {
    const obj: any = {};
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.quantity !== 0) {
      obj.quantity = message.quantity;
    }
    if (message.action !== 0) {
      obj.action = tradeActionToJSON(message.action);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTradeRequest>, I>>(base?: I): CreateTradeRequest {
    return CreateTradeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTradeRequest>, I>>(object: I): CreateTradeRequest {
    const message = createBaseCreateTradeRequest();
    message.symbol = object.symbol ?? "";
    message.quantity = object.quantity ?? 0;
    message.action = object.action ?? 0;
    return message;
  },
};

function createBaseCreateTradeResponse(): CreateTradeResponse {
  return { success: false, message: "", participant: undefined };
}

export const CreateTradeResponse: MessageFns<CreateTradeResponse> = {
  encode(message: CreateTradeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.participant !== undefined) {
      LadderParticipant.encode(message.participant, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTradeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTradeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.participant = LadderParticipant.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTradeResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      participant: isSet(object.participant) ? LadderParticipant.fromJSON(object.participant) : undefined,
    };
  },

  toJSON(message: CreateTradeResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.participant !== undefined) {
      obj.participant = LadderParticipant.toJSON(message.participant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTradeResponse>, I>>(base?: I): CreateTradeResponse {
    return CreateTradeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTradeResponse>, I>>(object: I): CreateTradeResponse {
    const message = createBaseCreateTradeResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    message.participant = (object.participant !== undefined && object.participant !== null)
      ? LadderParticipant.fromPartial(object.participant)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
